apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: gcp-wif
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane-gcp-provider
          containers:
            - name: package-runtime
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/run/secrets/gcp/cred-config.json
              volumeMounts:
                - name: gcp-wif
                  mountPath: /var/run/secrets/gcp
                  readOnly: true
                - name: gcp-token
                  mountPath: /var/run/secrets/gcp-token
                  readOnly: true
          volumes:
            - name: gcp-wif
              secret:
                secretName: gcp-wif-config
            - name: gcp-token
              projected:
                sources:
                  - serviceAccountToken:
                      audience: ${OIDC_ISSUER}
                      expirationSeconds: 3600
                      path: token
