apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  CLUSTER_NAME: kind-paidevo
  CLUSTER_PROVIDER: kind
  CLUSTER_TYPE: workload
  ENVIRONMENT: local
  ORG: paidevo
  OIDC_ID: paidevo-local
  GCP_PROJECT: bootstrap-491220
  GCP_SM_SECRET_NAME: manager-secrets
  GKE_LOCATION: ''
  WIF_PROJECT_NUMBER: '781189060618'
  OIDC_BUCKET: paidevo-local-oidc
  OIDC_ISSUER: https://storage.googleapis.com/paidevo-local-oidc/paidevo-local
  DOMAIN: yurikrupnik.com
  GATEWAY_MODE: platform
  GATEWAY_SUFFIX: platform.yurikrupnik.com
  INGRESS_CLASS: istio
  INGRESS_ENABLED: 'true'
  TLS_ENABLED: 'true'
  GITHUB_ACCOUNT: yurikrupnik
  GITHUB_REPO: nx-playground
  GITHUB_BRANCH: main
  POLICY_ACTION: Audit
  TLS_ISSUER: ca-local
  ACME_EMAIL: ''
