apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerg-shared-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: zerg-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://zerg:{{ .password }}@shared-postgres-rw.dbs.svc.cluster.local:5432/zerg"
  data:
    - secretKey: password
      remoteRef:
        key: manager-secrets
        property: dbs.zerg.password
