# GENERATED by `butler tilt gen` — DO NOT EDIT BY HAND.
# Repo-wide config: butler.toml. Per-app config: <app>/butler.toml.

local_resource(
    'postgres',
    serve_cmd='kubectl port-forward -n dbs deployment/postgres 5432:5432',
    labels=['port-forward'],
    readiness_probe=probe(
        period_secs=5,
        exec=exec_action(['sh', '-c', 'nc -z localhost 5432']),
    ),
)

local_resource(
    'redis',
    serve_cmd='kubectl port-forward -n dbs deployment/redis 6379:6379',
    labels=['port-forward'],
    readiness_probe=probe(
        period_secs=5,
        exec=exec_action(['sh', '-c', 'nc -z localhost 6379']),
    ),
)

local_resource(
    'mailhog',
    serve_cmd='kubectl port-forward -n dbs deployment/mailhog 8025:8025',
    labels=['port-forward'],
    readiness_probe=probe(
        period_secs=5,
        exec=exec_action(['sh', '-c', 'nc -z localhost 8025']),
    ),
)

k8s_yaml(kustomize('apps/zerg/shared/k8s/kustomize/overlays/dev'))
k8s_resource(
    objects=['zerg-shared-config:configmap', 'zerg-shared-secrets:secret'],
    new_name='zerg-shared-config',
    labels=['config'],
)

include('./apps/terran/api/Tiltfile')
include('./apps/terran/web/Tiltfile')
include('./apps/todo/api/Tiltfile')
include('./apps/todo/web/Tiltfile')
include('./apps/todo/web-astro/Tiltfile')
include('./apps/todo/web-htmx/Tiltfile')
include('./apps/todo/worker/Tiltfile')
include('./apps/zerg/api/Tiltfile')
include('./apps/zerg/email-nats/Tiltfile')
include('./apps/zerg/tasks/Tiltfile')
include('./apps/zerg/web/Tiltfile')
