apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: postgres-zerg-db-worker
  labels:
    app: postgres-zerg-db-worker
spec:
  scaleTargetRef:
    name: postgres-zerg-db-worker
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats.dbs.svc.cluster.local:8222"
        account: "$G"
        stream: "DB_TASKS_PG"
        consumer: "db-worker-postgres"
        lagThreshold: "10"
        activationLagThreshold: "1"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 50
              periodSeconds: 30
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 5
              periodSeconds: 15
