[package]
name = "core_config"
description = "Application configuration helpers: typed env parsing, app info, and tracing/OpenTelemetry initialization"
license.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
color-eyre = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry_sdk = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
temp-env = "0.3"
