apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../cert-manager/issuers/kind
  - ../../external-secrets/store/base
  - ../../crossplane/configs/kind
  - ../../kyverno/policies/base
