[package]
name = "domain_tasks"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
contract_tasks = { workspace = true, features = ["orm"] }
core_proc_macros = { workspace = true, features = ["sea_orm_resource"] }
database = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[lints]
workspace = true
