apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - ../../../base

namePrefix: neo4j-

replicas:
  - name: zerg-db-worker
    count: 1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: zerg-db-worker-config
    literals:
      - DB_BACKEND=neo4j
      - APP_PORT=8081
      - HEALTH_PORT=8081
      - NEO4J_URL=bolt://neo4j.dbs.svc.cluster.local:7687

secretGenerator:
  - name: zerg-db-worker-secrets
    literals:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j

patches:
  - patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/dapr.io~1app-id
        value: "db-worker-neo4j"
    target:
      kind: Deployment
      name: zerg-db-worker
