apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-mongo
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: "mongodb.dbs.svc.cluster.local:27017"
    - name: databaseName
      value: "zerg"
    - name: collectionName
      value: "dapr_state"
    - name: writeConcern
      value: "majority"
    - name: readConcern
      value: "majority"
