apiVersion: v1
kind: Service
metadata:
  name: zerg-db-worker
  labels:
    app: zerg-db-worker
spec:
  selector:
    app: zerg-db-worker
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
