[package]
name = "core_proc_macros"
description = "Facade re-exporting the ApiResource, SeaOrmResource, and SelectableFields derive macros"
license.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true

[features]
default = []
selectable_fields = ["dep:selectable_fields"]
api_resource = ["dep:api_resource"]
sea_orm_resource = ["dep:sea_orm_resource"]

[dependencies]
api_resource = { workspace = true, optional = true }
sea_orm_resource = { workspace = true, optional = true }
selectable_fields = { workspace = true, optional = true }

[lints]
workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
