apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: todo-proxy-envs
    literals:
      - upstream_host=todo-api
      - upstream_port=8080
      - upstream_name=backend
generatorOptions:
  disableNameSuffixHash: true
