//! `x` — one CLI and TUI over every HTTP API in this workspace.
//!
//! # Where the commands come from
//!
//! Nothing here enumerates routes. The command tree is derived from the
//! OpenAPI documents in `docs/openapi/`, which are themselves generated by the
//! `export_openapi_*` tests from the services' `#[utoipa::path]` annotations —
//! the same annotations that document the live `/api-docs/openapi.json`
//! endpoints. Adding a route to an axum router therefore adds a command here,
//! and a route that drifts from its annotation fails its invariant test before
//! it can mislead the CLI.
//!
//! That is the only thing a client can honestly share with these servers. The
//! handlers cannot be reused: four of the six `libs/domains/*` crates hard-
//! depend on sea-orm, sqlx and axum, so linking one into a CLI would drag a
//! database driver into a binary that only speaks HTTP.
//!
//! # Remote use
//!
//! The documents are embedded at compile time, so the binary is self-contained
//! and needs no checkout. `--spec <URL>` replaces the registry with a document
//! fetched from a running server, which is how the same binary drives a
//! deployment it was not built against.
//!
//! # Credentials
//!
//! Guarded routes are 401 to an anonymous client, so the document's
//! `components.securitySchemes` is read too: an operation's `security` list
//! names the credential, and `x` refuses to send a request the document
//! already says will be rejected. Two credentials are supported, matching the
//! two ingress paths of `libs/core/oidc-auth`'s `auth_required`:
//! `--token`/`$X_TOKEN` (`Authorization: Bearer <jwt>`, the machine path) and
//! `--session`/`$X_SESSION` (the opaque session id, sent under the cookie name
//! the document declares — the browser path). `just x-token` and
//! `just x-session` mint them against the local stack.
//!
//! A token wins when both are held: the middleware accepts a bearer JWT on
//! every guarded route, including the ones whose document declares only the
//! cookie because that is what the SPAs use.

pub mod command;
pub mod exec;
pub mod model;
pub mod render;
pub mod spec;
pub mod ui;

use std::io::{IsTerminal, Read};
use std::time::Duration;

use clap::ArgMatches;
use serde_json::Value;

use crate::model::{Api, Registry};
use crate::render::Format;
use crate::spec::Doc;

/// One entry per API *process*, not per resource: a process serves one
/// document, and the document's `servers[0].url` supplies the mount path.
///
/// `todo` and `zerg` both default to `:8080` because both services really do
/// default to `PORT=8080` (`libs/core/config/src/server.rs`,
/// `apps/zerg/api/src/config.rs`). Only one can hold that port locally, which
/// is what the per-API environment overrides are for; `x api list` prints the
/// resolved origin so the collision is visible rather than surprising.
const BUILTIN: [(&str, &str, &str, &str); 3] = [
    (
        "todo",
        include_str!("../../../../docs/openapi/todo.v1.json"),
        "X_TODO_URL",
        "http://127.0.0.1:8080",
    ),
    (
        "zerg",
        include_str!("../../../../docs/openapi/zerg.v1.json"),
        "X_ZERG_URL",
        "http://127.0.0.1:8080",
    ),
    (
        "terran",
        include_str!("../../../../docs/openapi/terran.v1.json"),
        "X_TERRAN_URL",
        "http://127.0.0.1:8081",
    ),
];

/// Build the registry from the embedded documents.
pub fn builtin_registry() -> eyre::Result<Registry> {
    let mut apis = Vec::with_capacity(BUILTIN.len());
    for (key, raw, env_key, fallback) in BUILTIN {
        apis.push(Api {
            key: key.to_owned(),
            origin: std::env::var(env_key).unwrap_or_else(|_| fallback.to_owned()),
            doc: Doc::parse(key, raw)?,
        });
    }
    Ok(Registry::build(apis))
}

/// Load a single document from a path or URL, replacing the registry.
///
/// A URL also supplies the origin: fetching
/// `https://todo.example.com/api-docs/openapi.json` means the operations live
/// on `https://todo.example.com`, which is exactly the remote-worker case and
/// removes the need to pass `--base-url` alongside `--spec`.
pub async fn remote_registry(source: &str) -> eyre::Result<Registry> {
    let (raw, origin) = if source.starts_with("http://") || source.starts_with("https://") {
        let response = reqwest::get(source)
            .await
            .map_err(|e| eyre::eyre!("{source} unreachable: {e}"))?
            .error_for_status()
            .map_err(|e| eyre::eyre!("{source}: {e}"))?;
        let text = response.text().await?;
        let origin = origin_of(source)?;
        (text, origin)
    } else {
        let text = std::fs::read_to_string(source)
            .map_err(|e| eyre::eyre!("cannot read spec `{source}`: {e}"))?;
        (text, String::new())
    };

    let doc = Doc::parse(source, &raw)?;
    Ok(Registry::build(vec![Api {
        key: "remote".to_owned(),
        origin,
        doc,
    }]))
}

/// `scheme://host[:port]` of a URL, without pulling in a URL parser for the
/// one thing this binary needs from one.
fn origin_of(url: &str) -> eyre::Result<String> {
    let (scheme, rest) = url
        .split_once("://")
        .ok_or_else(|| eyre::eyre!("`{url}` is not an absolute URL"))?;
    let authority = rest.split('/').next().unwrap_or_default();
    if authority.is_empty() {
        return Err(eyre::eyre!("`{url}` has no host"));
    }
    Ok(format!("{scheme}://{authority}"))
}

/// clap cannot parse `--spec` for us: the value decides which subcommands
/// exist, so it has to be read before the command tree is built. Scanning argv
/// directly is the standard move for a dynamically-shaped CLI; it accepts both
/// `--spec X` and `--spec=X` and nothing else, so a mis-spelling still reaches
/// clap and gets clap's error.
pub fn prescan_spec<I, S>(args: I) -> Option<String>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut iter = args.into_iter().peekable();
    while let Some(arg) = iter.next() {
        let arg = arg.as_ref();
        if let Some(value) = arg.strip_prefix("--spec=") {
            return Some(value.to_owned());
        }
        if arg == "--spec" || arg == "-s" {
            return iter.next().map(|v| v.as_ref().to_owned());
        }
    }
    None
}

/// `--body` accepts inline JSON, `@path`, or `-` for stdin.
pub fn read_body(raw: &str) -> eyre::Result<Value> {
    let text = match raw {
        "-" => {
            let mut buffer = String::new();
            std::io::stdin().read_to_string(&mut buffer)?;
            buffer
        }
        other => match other.strip_prefix('@') {
            Some(path) => std::fs::read_to_string(path)
                .map_err(|e| eyre::eyre!("cannot read --body file `{path}`: {e}"))?,
            None => other.to_owned(),
        },
    };
    serde_json::from_str(&text).map_err(|e| eyre::eyre!("--body is not valid JSON: {e}"))
}

/// `x api list`.
pub fn api_list(registry: &Registry) -> String {
    let mut out = String::new();
    for (index, api) in registry.apis.iter().enumerate() {
        out.push_str(&format!(
            "{} — {} v{}\n  origin {}{}\n",
            api.key,
            api.doc.info.title,
            api.doc.info.version,
            api.origin,
            api.doc.mount()
        ));
        let mut ops: Vec<&crate::model::Op> =
            registry.ops.iter().filter(|o| o.api == index).collect();
        ops.sort_by(|a, b| (&a.resource, &a.verb).cmp(&(&b.resource, &b.verb)));
        for op in ops {
            out.push_str(&format!(
                "    x {:<22} {:<16} {:<6} {:<28} {}\n",
                op.verb,
                op.resource,
                op.method.to_uppercase(),
                op.path,
                op.operation_id
            ));
        }
        out.push('\n');
    }
    out
}

pub struct Globals {
    pub format: Format,
    pub fields: Option<Vec<String>>,
    pub dry_run: bool,
    pub token: Option<String>,
    /// Value of the session cookie whose *name* comes from the document's
    /// `securitySchemes` — the browser credential every guarded service here
    /// declares, and the one a CLI can obtain from its own login route.
    pub session: Option<String>,
    pub headers: Vec<(String, String)>,
    pub timeout: Duration,
    pub base_url: Option<String>,
    pub api: Option<String>,
    pub op: Option<String>,
}

impl Globals {
    pub fn from_matches(matches: &ArgMatches) -> eyre::Result<Self> {
        let headers = matches
            .get_many::<String>("header")
            .map(|values| values.map(|v| exec::parse_header(v)).collect())
            .transpose()?
            .unwrap_or_default();

        Ok(Self {
            format: Format::resolve(
                matches.get_one::<String>("output").map(String::as_str),
                std::io::stdout().is_terminal(),
            ),
            fields: matches.get_one::<String>("fields").map(|raw| {
                raw.split(',')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .map(str::to_owned)
                    .collect()
            }),
            dry_run: matches.get_flag("dry-run"),
            // An empty value counts as absent: `export X_TOKEN=$(…)` after a
            // failed mint leaves an empty variable, and sending
            // `Authorization: Bearer ` is a worse error than sending nothing.
            token: credential(matches, "token", "X_TOKEN"),
            session: credential(matches, "session", "X_SESSION"),
            headers,
            timeout: Duration::from_secs(*matches.get_one::<u64>("timeout").unwrap_or(&30)),
            base_url: matches.get_one::<String>("base-url").cloned(),
            api: matches.get_one::<String>("api").cloned(),
            op: matches.get_one::<String>("op").cloned(),
        })
    }
}

/// A credential from its flag, falling back to its environment variable, with
/// empty values treated as absent in both places.
fn credential(matches: &ArgMatches, flag: &str, env_key: &str) -> Option<String> {
    matches
        .get_one::<String>(flag)
        .cloned()
        .or_else(|| std::env::var(env_key).ok())
        .filter(|value| !value.trim().is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn spec_prescan_reads_both_spellings_and_nothing_else() {
        assert_eq!(
            prescan_spec(["x", "--spec", "a.json", "get", "todos"]),
            Some("a.json".to_owned())
        );
        assert_eq!(
            prescan_spec(["x", "get", "todos", "--spec=b.json"]),
            Some("b.json".to_owned())
        );
        // A typo must fall through to clap, which produces a real error,
        // rather than being half-recognised here.
        assert_eq!(prescan_spec(["x", "--specs", "c.json"]), None);
        assert_eq!(prescan_spec(["x", "get", "todos"]), None);
    }

    #[test]
    fn a_spec_url_supplies_its_own_origin() {
        // This is what makes `x --spec https://host/api-docs/openapi.json get
        // todos` work without also passing --base-url.
        assert_eq!(
            origin_of("https://todo.example.com/api-docs/openapi.json").expect("parses"),
            "https://todo.example.com"
        );
        assert_eq!(
            origin_of("http://127.0.0.1:8080/api-docs/openapi.json").expect("parses"),
            "http://127.0.0.1:8080"
        );
        assert!(origin_of("not-a-url").is_err());
    }

    #[test]
    fn body_accepts_inline_json() {
        assert_eq!(
            read_body(r#"{"title":"x"}"#).expect("parses"),
            serde_json::json!({"title": "x"})
        );
        assert!(read_body("{not json").is_err());
    }
}
