//! `butler k8s gen` — the values files an app deploys from, and the manifests
//! the published `app` KCL package renders from them.
//!
//! One config surface, one renderer. An app declares a `[workload]` in its
//! `butler.toml` and nothing else: no `values.yaml` to keep in step, no
//! `main.k`, no `kcl.mod`, no kustomize overlay. `butler k8s gen` writes
//!
//! ```text
//! <app>/k8s/values.yaml          the merged workload, one per app
//! <app>/k8s/values.<env>.yaml    that environment's diffs, one per env
//! manifests/k8s/apps/<name>.yaml the rendered objects
//! manifests/k8s/apps/kustomization.yaml
//! ```
//!
//! and `--check` fails when any of them has drifted, exactly like the
//! Tiltfiles.
//!
//! ## Pass-through, not modelling
//!
//! `[workload]`, `[externalSecret]` and their per-env overlays are opaque TOML:
//! butler serialises them to YAML 1:1 and never enumerates a schema key. The
//! KCL package owns the schema and is what rejects an unknown or mistyped
//! field, so a package release adds fields without a butler release. See
//! [`crate::settings::Root::workload_defaults`].
//!
//! ## What butler does own
//!
//! The `image` reference, which must have exactly one home: the image facts
//! ([`crate::tilt::image_facts`]) that also drive the Tiltfile's
//! `docker_build` and CI's `container` target. A workload table that declares
//! `image` is a hard error, not an override — that is the duplication this
//! whole flow exists to kill.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use eyre::{Result, bail, eyre};
use toml::Value;
use toml::value::Table;

use crate::graph::ProjectGraph;
use crate::settings::{self, App, AppEnv, AppOverrides, Root};
use crate::tilt;

/// Where every rendered manifest lands, workspace-root-relative: root
/// `butler.toml` `[k8s] outDir`, with `{env}` expanded so a repo that renders
/// several environments can keep them side by side
/// (`outDir = "manifests/k8s/{env}"`).
///
/// `[k8s] extraResources` entries are relative to this directory, so moving it
/// to a different depth means fixing those paths too — the generated aggregate
/// lives here and kustomize resolves them from it.
pub fn out_dir(root: &Root) -> String {
    root.k8s.out_dir.replace("{env}", &root.env)
}

/// The container port the KCL package's `Workload` schema defaults to. Spelled
/// here because Tilt has to forward to the port the app will actually listen
/// on, and an app that takes the default declares no `port` at all.
pub(crate) const DEFAULT_PORT: u16 = 8080;

const GENERATED: &str = "# GENERATED by `butler k8s gen` — DO NOT EDIT BY HAND.";

// ---------------------------------------------------------------------------
// Entry point

/// Which files to write, and which app set to consider. Mirrors
/// [`crate::tilt::Selection`] so the nx plugin drives both the same way.
#[derive(Default)]
pub struct Selection<'a> {
    /// Write only this app's values files and rendered manifest.
    pub app: Option<&'a str>,
    /// Write only the aggregate `kustomization.yaml`.
    pub root_only: bool,
    /// Authoritative app directories; empty = every app with a `[workload]`.
    pub apps: &'a [String],
}

/// Generate the k8s artifacts. Returns workspace-root-relative path -> content.
pub fn generate(
    workspace_root: &Path,
    graph: &ProjectGraph,
    root: &Root,
    overrides: &AppOverrides,
    selection: &Selection<'_>,
) -> Result<BTreeMap<String, String>> {
    let mut dirs: Vec<&String> = overrides
        .iter()
        .filter(|(_, app)| app.workload.is_some())
        .map(|(dir, _)| dir)
        .collect();
    if !selection.apps.is_empty() {
        // The nx plugin's authoritative list, narrowed to the apps that deploy:
        // an image-only app is in the container set but has no workload.
        let allowed: BTreeSet<&str> = selection.apps.iter().map(String::as_str).collect();
        dirs.retain(|dir| allowed.contains(dir.as_str()));
    }
    if let Some(want) = selection.app
        && !dirs.iter().any(|dir| *dir == want)
    {
        bail!(
            "{want} deploys nothing: add a [workload] table to {want}/{file}",
            file = settings::FILE
        );
    }
    if dirs.is_empty() {
        bail!(
            "no app declares a [workload]: an app joins the k8s flow by adding \
             one to its {file}, and inherits the repo-wide shape from \
             [workloadDefaults.<kind>] in the root {file}",
            file = settings::FILE
        );
    }

    let apps: Vec<WorkloadApp> = dirs
        .iter()
        .map(|dir| resolve(workspace_root, graph, root, dir, &overrides[*dir]))
        .collect::<Result<_>>()?;

    let want_root = selection.app.is_none();
    let want_apps = !selection.root_only;

    let mut files = BTreeMap::new();
    if want_apps {
        for app in apps
            .iter()
            .filter(|a| selection.app.is_none_or(|want| a.dir == want))
        {
            let values = values_files(root, app)?;
            for (name, body) in &values {
                files.insert(format!("{}/k8s/{name}", app.dir), body.clone());
            }
            files.insert(
                format!("{}/{}.yaml", out_dir(root), app.name),
                render(root, app, &values)?,
            );
        }
    }
    if want_root {
        files.insert(
            format!("{}/kustomization.yaml", out_dir(root)),
            kustomization(root, &apps),
        );
    }
    Ok(files)
}

// ---------------------------------------------------------------------------
// Resolution

/// An app that deploys something: everything the values files need, with the
/// workload payload still opaque.
struct WorkloadApp {
    /// Workspace-root-relative app directory.
    dir: String,
    /// `<dir>/butler.toml`, for error messages that name where to make the fix.
    file: String,
    /// Image basename (`todo-web-htmx`) — the workload name, the Tilt resource
    /// and the rendered file's stem, all one string.
    name: String,
    /// Image repository with the registry substituted and no tag.
    repository: String,
    /// Product segment of the app path; the namespace and `partOf`.
    product: String,
    kind: tilt::Kind,
    /// The app's own `[workload]`, verbatim.
    declared: Value,
    config: Option<BTreeMap<String, String>>,
    external_secret: Option<Value>,
    /// Every environment this app gets a values file for: the ones it declares
    /// plus every one the repo knows. An environment with no diffs still needs
    /// a file — the package hard-errors on a missing overlay for `-D env=`.
    envs: BTreeMap<String, AppEnv>,
}

fn resolve(
    workspace_root: &Path,
    graph: &ProjectGraph,
    root: &Root,
    dir: &str,
    app: &App,
) -> Result<WorkloadApp> {
    let project = graph
        .projects
        .values()
        .find(|p| p.root == *dir)
        .ok_or_else(|| eyre!("{dir} declares a [workload] but is not a discovered project"))?;
    let kind = tilt::app_kind(workspace_root, dir).ok_or_else(|| {
        eyre!(
            "{dir}: no {markers}; unsupported app kind",
            markers = tilt::KIND_MARKERS
        )
    })?;
    let facts = tilt::image_facts(root, &kind, dir, project, app.image.as_ref())?;
    let repository = tilt::image_from_tag(&facts.tag, &root.registry);
    let name = repository
        .rsplit('/')
        .next()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| eyre!("{dir}: cannot derive a workload name from image `{repository}`"))?
        .to_string();

    let mut envs: BTreeMap<String, AppEnv> = app.env.clone();
    for env in repo_envs(root) {
        envs.entry(env).or_default();
    }

    Ok(WorkloadApp {
        dir: dir.to_string(),
        file: format!("{dir}/{}", settings::FILE),
        name,
        repository,
        product: product(dir),
        kind,
        declared: app
            .workload
            .clone()
            .expect("callers filter on a declared workload"),
        config: app.config.clone(),
        external_secret: app.external_secret.clone(),
        envs,
    })
}

/// Every environment the repo deploys: the default one plus every one that
/// pins an image tag.
fn repo_envs(root: &Root) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    out.insert(root.env.clone());
    out.extend(root.k8s.image_tag.keys().cloned());
    out
}

/// The product an app belongs to: the segment below `apps/`
/// (`apps/todo/api` -> `todo`), else the app directory name, else `default` for
/// a single-app repo. The namespace, `partOf` and Tilt's KCL render all use it,
/// so it is derived once.
pub(crate) fn product(dir: &str) -> String {
    dir.split('/')
        .nth(1)
        .or_else(|| dir.split('/').next_back())
        .filter(|s| !s.is_empty() && *s != ".")
        .unwrap_or("default")
        .to_string()
}

/// The image an environment deploys: the repository the image facts own, tagged
/// with what the root `[k8s.imageTag]` maps that environment to — its own name
/// when it maps nothing, so `dev` renders `:dev` unconfigured.
fn image_ref(root: &Root, app: &WorkloadApp, env: &str) -> String {
    let tag = root.k8s.image_tag.get(env).map_or(env, String::as_str);
    format!("{}:{tag}", app.repository)
}

// ---------------------------------------------------------------------------
// Merging

/// Deep, right-wins merge — the same semantics the KCL package uses to layer
/// `values.<env>.yaml` over `values.yaml`, and kustomize to layer an overlay
/// over a base: nested tables merge recursively, scalars and arrays replace
/// wholesale, and a key only the right side has is added.
///
/// Arrays replace rather than append because appending has no useful inverse:
/// an environment that needs one fewer `env` entry could not express it.
pub(crate) fn merge(
    defaults: Option<&Value>,
    app: Option<&Value>,
    overlay: Option<&Value>,
) -> Value {
    let mut out = Value::Table(Table::new());
    for layer in [defaults, app, overlay].into_iter().flatten() {
        merge_into(&mut out, layer);
    }
    out
}

fn merge_into(base: &mut Value, over: &Value) {
    match (base, over) {
        (Value::Table(into), Value::Table(from)) => {
            for (key, value) in from {
                match into.get_mut(key) {
                    Some(existing) => merge_into(existing, value),
                    None => {
                        into.insert(key.clone(), value.clone());
                    }
                }
            }
        }
        (base, over) => *base = over.clone(),
    }
}

/// The workload an app deploys in one environment: the repo-wide shape for its
/// kind, its own `[workload]`, that environment's `[env.<env>.workload]`.
/// `None` when the app declares no workload at all.
///
/// Shared with the Tiltfile renderer, which needs the merged `port` to compose
/// `port_forwards`.
pub(crate) fn merged_workload(
    root: &Root,
    app: &App,
    kind: tilt::Kind,
    env: &str,
) -> Option<Value> {
    let declared = app.workload.as_ref()?;
    Some(merge(
        root.workload_defaults.get(kind.name()),
        Some(declared),
        app.env.get(env).and_then(|e| e.workload.as_ref()),
    ))
}

/// The container port a merged workload listens on, mirroring the package's own
/// default for a workload that declares none.
pub(crate) fn workload_port(workload: &Value) -> u16 {
    workload
        .get("port")
        .and_then(Value::as_integer)
        .and_then(|p| u16::try_from(p).ok())
        .unwrap_or(DEFAULT_PORT)
}

// ---------------------------------------------------------------------------
// Values files

/// Every values file one app needs, keyed by bare filename.
fn values_files(root: &Root, app: &WorkloadApp) -> Result<BTreeMap<String, String>> {
    reject_declared_image(root, app)?;
    let mut out = BTreeMap::new();
    out.insert("values.yaml".to_string(), values_for(root, app, None)?);
    for env in app.envs.keys() {
        out.insert(
            format!("values.{env}.yaml"),
            values_for(root, app, Some(env))?,
        );
    }
    Ok(out)
}

/// One values file. `env = None` is the base `values.yaml`: the fully merged
/// workload, tagged for the repo's default environment. `Some(env)` is the
/// `values.<env>.yaml` overlay, which carries only that environment's diffs
/// plus its own image tag — the package deep-merges it over the base, so
/// restating the base there would only be a second place to keep in step.
fn values_for(root: &Root, app: &WorkloadApp, env: Option<&str>) -> Result<String> {
    let overlay = env.and_then(|e| app.envs.get(e));
    let mut workload = match env {
        None => merge(
            root.workload_defaults.get(app.kind.name()),
            Some(&app.declared),
            None,
        ),
        Some(_) => overlay
            .and_then(|o| o.workload.clone())
            .unwrap_or_else(|| Value::Table(Table::new())),
    };
    let table = workload
        .as_table_mut()
        .ok_or_else(|| eyre!("{}: [workload] must be a table", app.file))?;

    let active = env.unwrap_or(&root.env);
    table.insert(
        "image".to_string(),
        Value::String(image_ref(root, app, active)),
    );
    if env.is_none() {
        // Defaults, not decrees: an app that spells one of these out keeps it.
        for (key, value) in [
            ("name", &app.name),
            ("namespace", &app.product),
            ("partOf", &app.product),
        ] {
            table
                .entry(key.to_string())
                .or_insert_with(|| Value::String(value.clone()));
        }
    }

    let (config, external_secret) = match overlay {
        Some(o) => (o.config.as_ref(), o.external_secret.as_ref()),
        None => (app.config.as_ref(), app.external_secret.as_ref()),
    };

    let mut release = serde_yaml_ng::Mapping::new();
    release.insert(yaml_key("workload"), to_yaml(&workload));
    if let Some(config) = config {
        let data: serde_yaml_ng::Mapping = config
            .iter()
            .map(|(k, v)| (yaml_key(k), serde_yaml_ng::Value::String(v.clone())))
            .collect();
        release.insert(yaml_key("config"), serde_yaml_ng::Value::Mapping(data));
    }
    if let Some(secret) = external_secret {
        release.insert(yaml_key("externalSecret"), to_yaml(secret));
    }

    let body = serde_yaml_ng::to_string(&serde_yaml_ng::Value::Mapping(release)).map_err(|e| {
        eyre!(
            "{}: serialising values for {app_env}: {e}",
            app.file,
            app_env = env.unwrap_or("the base")
        )
    })?;
    Ok(format!("{}\n{body}", header(app, env)))
}

fn header(app: &WorkloadApp, env: Option<&str>) -> String {
    match env {
        None => format!(
            "{GENERATED}\n# Source: {file} [workload] over {root} \
             [workloadDefaults.{kind}].",
            file = app.file,
            root = settings::FILE,
            kind = app.kind.name(),
        ),
        Some(env) => format!(
            "{GENERATED}\n# Source: {file} [env.{env}] — diffs the package \
             deep-merges over values.yaml.",
            file = app.file,
        ),
    }
}

/// The one key butler refuses to take from a workload table.
///
/// The image reference has a single home — the app's `[image]` or the root
/// `[imageDefaults.<kind>]` — and butler stamps it in per environment from
/// there, so the Tiltfile, CI and the manifest can never name three different
/// images. Every layer that could smuggle one in is checked, and the error
/// names the file and the table to edit.
fn reject_declared_image(root: &Root, app: &WorkloadApp) -> Result<()> {
    let declares = |value: Option<&Value>| {
        value
            .and_then(Value::as_table)
            .is_some_and(|t| t.contains_key("image"))
    };
    let kind = app.kind.name();
    let sources: [(bool, String, String); 2] = [
        (
            declares(root.workload_defaults.get(kind)),
            settings::FILE.to_string(),
            format!("[workloadDefaults.{kind}]"),
        ),
        (
            declares(Some(&app.declared)),
            app.file.clone(),
            "[workload]".to_string(),
        ),
    ];
    for (declared, file, table) in sources {
        if declared {
            return Err(image_is_not_yours(&file, &table));
        }
    }
    for (env, overlay) in &app.envs {
        if declares(overlay.workload.as_ref()) {
            return Err(image_is_not_yours(
                &app.file,
                &format!("[env.{env}.workload]"),
            ));
        }
    }
    Ok(())
}

fn image_is_not_yours(file: &str, table: &str) -> eyre::Report {
    eyre!(
        "{file}: {table} declares `image`, which butler owns. The reference is \
         derived from the app's `[image]` or the root `[imageDefaults.<kind>]` \
         plus the environment's tag, so that the Tiltfile, CI and the rendered \
         manifest cannot name three different images. Remove the key."
    )
}

// ---------------------------------------------------------------------------
// TOML -> YAML

fn yaml_key(key: &str) -> serde_yaml_ng::Value {
    serde_yaml_ng::Value::String(key.to_string())
}

/// TOML value -> YAML value, 1:1. The conversion is explicit rather than
/// `Serialize`-driven so that TOML's date/time literals — which have no
/// counterpart in the package's schema — reach KCL as the text the author
/// wrote instead of serde's private tagged representation.
fn to_yaml(value: &Value) -> serde_yaml_ng::Value {
    use serde_yaml_ng::Value as Y;
    match value {
        Value::String(s) => Y::String(s.clone()),
        Value::Integer(i) => Y::Number((*i).into()),
        Value::Float(f) => Y::Number((*f).into()),
        Value::Boolean(b) => Y::Bool(*b),
        Value::Datetime(d) => Y::String(d.to_string()),
        Value::Array(items) => Y::Sequence(items.iter().map(to_yaml).collect()),
        Value::Table(table) => Y::Mapping(
            table
                .iter()
                .map(|(k, v)| (yaml_key(k), to_yaml(v)))
                .collect(),
        ),
    }
}

// ---------------------------------------------------------------------------
// Rendering through the package

/// The `kcl run` invocation that turns values files into manifests — one
/// spelling, shared by `butler k8s gen` and the Tiltfile it renders, so the dev
/// loop and the committed manifests cannot come from different packages.
pub(crate) fn render_command(root: &Root) -> String {
    format!("kcl run \"{}\" -D env={} -q", package_ref(root), root.env)
}

fn package_ref(root: &Root) -> String {
    match &root.k8s.tag {
        Some(tag) => format!("{}?tag={tag}", root.k8s.package),
        None => root.k8s.package.clone(),
    }
}

/// Render one app through the package.
///
/// The values files go to a scratch directory first, so `gen` and `--check`
/// render from exactly the bytes butler just computed — never from a stale
/// values file, and never disturbed by a leftover `kcl.mod` in the app tree.
fn render(root: &Root, app: &WorkloadApp, values: &BTreeMap<String, String>) -> Result<String> {
    let scratch = Scratch::new(&app.name)?;
    for (name, body) in values {
        std::fs::write(scratch.0.join(name), body)
            .map_err(|e| eyre!("writing {name} for {}: {e}", app.dir))?;
    }

    let package = package_ref(root);
    let output = Command::new("kcl")
        .arg("run")
        .arg(&package)
        .arg("-D")
        .arg(format!("env={}", root.env))
        .arg("-q")
        .current_dir(&scratch.0)
        .output()
        .map_err(|e| {
            eyre!(
                "running `kcl` for {}: {e}\n\
                 the k8s artifacts are rendered by the {package} KCL package; \
                 install kcl (https://kcl-lang.io) to generate them",
                app.dir
            )
        })?;

    let stderr = String::from_utf8_lossy(&output.stderr);
    if !output.status.success() {
        bail!(
            "{}: `{}` failed ({}):\n{}",
            app.dir,
            render_command(root),
            output.status,
            stderr.trim_end()
        );
    }
    let manifests = String::from_utf8_lossy(&output.stdout);
    if manifests.trim().is_empty() {
        bail!(
            "{}: `{}` rendered nothing — the [workload] payload produced no \
             objects.{}",
            app.dir,
            render_command(root),
            if stderr.trim().is_empty() {
                String::new()
            } else {
                format!("\n{}", stderr.trim_end())
            }
        );
    }

    Ok(format!(
        "{GENERATED}\n\
         # Source: {file} [workload], rendered by {package} (env {env}).\n\
         {manifests}",
        file = app.file,
        env = root.env,
    ))
}

/// The aggregate: one entry per rendered app, so `kubectl apply -k` or an
/// ArgoCD application points at a single directory.
///
/// `[k8s] extraResources` is appended verbatim. It exists for objects that are
/// environment fixtures rather than workload shape — the dev-only placeholder
/// Secrets, for instance, which the package cannot render (it emits
/// ExternalSecrets) and which would otherwise scatter dummy credentials across
/// every app's config.
fn kustomization(root: &Root, apps: &[WorkloadApp]) -> String {
    let mut names: Vec<&str> = apps.iter().map(|a| a.name.as_str()).collect();
    names.sort_unstable();
    let mut out = format!(
        "# GENERATED by `butler k8s gen --root` — DO NOT EDIT BY HAND.\n\
         # One entry per app with a [workload] in its {file}, plus the\n\
         # [k8s] extraResources that file lists.\n\
         apiVersion: kustomize.config.k8s.io/v1beta1\n\
         kind: Kustomization\n\
         resources:\n",
        file = settings::FILE,
    );
    for name in names {
        let _ = writeln!(out, "  - {name}.yaml");
    }
    for extra in &root.k8s.extra_resources {
        let _ = writeln!(out, "  - {extra}");
    }
    out
}

/// A directory that exists only for the duration of one render.
struct Scratch(PathBuf);

impl Scratch {
    fn new(name: &str) -> Result<Self> {
        use std::sync::atomic::{AtomicU32, Ordering};
        static SEQ: AtomicU32 = AtomicU32::new(0);
        let dir = std::env::temp_dir().join(format!(
            "butler-k8s-{}-{}-{name}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed),
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir)
            .map_err(|e| eyre!("creating a render scratch dir at {}: {e}", dir.display()))?;
        Ok(Self(dir))
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn value(toml_src: &str) -> Value {
        toml::from_str(toml_src).expect("test fixture parses")
    }

    fn root(extra: &str) -> Root {
        toml::from_str(&format!(
            "registry = 'acme'\n\
             [k8s]\ntag = '0.1.2'\n\
             [k8s.imageTag]\ndev = 'dev'\nprod = 'main'\n{extra}"
        ))
        .expect("test root config parses")
    }

    fn app(declared: &str) -> WorkloadApp {
        WorkloadApp {
            dir: "apps/todo/api".into(),
            file: "apps/todo/api/butler.toml".into(),
            name: "todo-api".into(),
            repository: "acme/todo-api".into(),
            product: "todo".into(),
            kind: tilt::Kind::Service,
            declared: value(declared),
            config: None,
            external_secret: None,
            envs: BTreeMap::from([
                ("dev".to_string(), AppEnv::default()),
                ("prod".to_string(), AppEnv::default()),
            ]),
        }
    }

    #[test]
    fn merge_is_deep_and_right_wins() {
        let defaults = value(
            "replicas = 1\nport = 8080\n\
             [resources.requests]\nmemory = '128Mi'\ncpu = '250m'\n\
             [resources.limits]\nmemory = '512Mi'\n",
        );
        let declared = value(
            "replicas = 2\n\
             [resources.requests]\nmemory = '256Mi'\n",
        );
        let merged = merge(Some(&defaults), Some(&declared), None);

        // Right wins on a scalar the app restates...
        assert_eq!(merged["replicas"].as_integer(), Some(2));
        // ...the default survives where the app is silent...
        assert_eq!(merged["port"].as_integer(), Some(8080));
        // ...and a nested table merges instead of replacing, so overriding one
        // request does not drop the cpu request or the limits table.
        assert_eq!(
            merged["resources"]["requests"]["memory"].as_str(),
            Some("256Mi")
        );
        assert_eq!(
            merged["resources"]["requests"]["cpu"].as_str(),
            Some("250m")
        );
        assert_eq!(
            merged["resources"]["limits"]["memory"].as_str(),
            Some("512Mi")
        );
    }

    #[test]
    fn merge_replaces_arrays_wholesale() {
        let base = value("[[env]]\nname = 'A'\nvalue = '1'\n[[env]]\nname = 'B'\nvalue = '2'\n");
        let over = value("[[env]]\nname = 'A'\nvalue = 'overridden'\n");
        let merged = merge(Some(&base), Some(&over), None);
        let env = merged["env"].as_array().expect("env array");
        assert_eq!(
            env.len(),
            1,
            "an overlay array replaces, never appends: {env:?}"
        );
        assert_eq!(env[0]["value"].as_str(), Some("overridden"));
    }

    #[test]
    fn merge_layers_the_env_overlay_last() {
        let merged = merge(
            Some(&value("replicas = 1")),
            Some(&value("replicas = 2")),
            Some(&value("replicas = 5")),
        );
        assert_eq!(merged["replicas"].as_integer(), Some(5));
    }

    #[test]
    fn butler_injects_the_image_name_namespace_and_part_of() {
        let root = root("[workloadDefaults.service]\nreplicas = 1\n");
        let values = values_for(&root, &app("component = 'api-server'"), None).expect("values");

        assert!(values.contains("image: acme/todo-api:dev"), "{values}");
        assert!(values.contains("name: todo-api"), "{values}");
        assert!(values.contains("namespace: todo"), "{values}");
        assert!(values.contains("partOf: todo"), "{values}");
        // The kind default reached the file, and so did the app's own key.
        assert!(values.contains("replicas: 1"), "{values}");
        assert!(values.contains("component: api-server"), "{values}");
    }

    #[test]
    fn an_app_may_override_the_injected_name_and_namespace() {
        let root = root("");
        let values = values_for(
            &root,
            &app("name = 'legacy-todo'\nnamespace = 'shared'\npartOf = 'platform'"),
            None,
        )
        .expect("values");
        assert!(values.contains("name: legacy-todo"), "{values}");
        assert!(values.contains("namespace: shared"), "{values}");
        assert!(values.contains("partOf: platform"), "{values}");
        // The image is still butler's, whatever else the app renames.
        assert!(values.contains("image: acme/todo-api:dev"), "{values}");
    }

    #[test]
    fn a_declared_image_is_rejected_by_the_file_and_the_table() {
        let bare = root("");
        let err = values_files(&bare, &app("image = 'yurikrupnik/todo-api:dev'"))
            .expect_err("the image has one home");
        let msg = err.to_string();
        assert!(msg.contains("apps/todo/api/butler.toml"), "{msg}");
        assert!(msg.contains("[workload]"), "{msg}");

        // Same for the repo-wide shape...
        let with_default = root("[workloadDefaults.service]\nimage = 'acme/x:1'\n");
        let err = values_files(&with_default, &app("replicas = 1")).expect_err("nor repo-wide");
        assert!(
            err.to_string().contains("[workloadDefaults.service]"),
            "{err}"
        );

        // ...and for an env overlay that tries to smuggle one in.
        let mut smuggler = app("replicas = 1");
        smuggler.envs.insert(
            "prod".to_string(),
            AppEnv {
                workload: Some(value("image = 'acme/x:1'")),
                ..AppEnv::default()
            },
        );
        let err = values_files(&bare, &smuggler).expect_err("nor per env");
        assert!(err.to_string().contains("[env.prod.workload]"), "{err}");
    }

    #[test]
    fn a_minimal_app_renders_a_complete_values_file() {
        let root = root("[workloadDefaults.service]\nreplicas = 1\nport = 8080\n");
        let mut minimal = app("component = 'api-server'");
        minimal.config = Some(BTreeMap::from([
            ("PORT".to_string(), "8080".to_string()),
            ("RATE_LIMIT_ENABLED".to_string(), "true".to_string()),
        ]));
        let values = values_for(&root, &minimal, None).expect("values");

        assert_eq!(
            values,
            "# GENERATED by `butler k8s gen` — DO NOT EDIT BY HAND.\n\
             # Source: apps/todo/api/butler.toml [workload] over butler.toml [workloadDefaults.service].\n\
             workload:\n  \
               component: api-server\n  \
               image: acme/todo-api:dev\n  \
               name: todo-api\n  \
               namespace: todo\n  \
               partOf: todo\n  \
               port: 8080\n  \
               replicas: 1\n\
             config:\n  \
               PORT: '8080'\n  \
               RATE_LIMIT_ENABLED: 'true'\n",
            "{values}"
        );
    }

    #[test]
    fn an_env_file_carries_only_that_env_diffs_and_its_own_tag() {
        let root = root("[workloadDefaults.service]\nreplicas = 1\n");
        let mut app = app("component = 'api-server'");
        app.envs.insert(
            "prod".to_string(),
            AppEnv {
                workload: Some(value("replicas = 3")),
                config: Some(BTreeMap::from([(
                    "LOG_LEVEL".to_string(),
                    "warn".to_string(),
                )])),
                external_secret: Some(value("store = 'gcp'")),
            },
        );
        let values = values_for(&root, &app, Some("prod")).expect("values");

        assert_eq!(
            values,
            "# GENERATED by `butler k8s gen` — DO NOT EDIT BY HAND.\n\
             # Source: apps/todo/api/butler.toml [env.prod] — diffs the package deep-merges over values.yaml.\n\
             workload:\n  \
               image: acme/todo-api:main\n  \
               replicas: 3\n\
             config:\n  \
               LOG_LEVEL: warn\n\
             externalSecret:\n  \
               store: gcp\n",
            "{values}"
        );
    }

    #[test]
    fn every_env_the_repo_knows_gets_a_file() {
        let root = root("[workloadDefaults.service]\nreplicas = 1\n");
        let files = values_files(&root, &app("component = 'api-server'")).expect("values files");
        assert_eq!(
            files.keys().collect::<Vec<_>>(),
            vec!["values.dev.yaml", "values.prod.yaml", "values.yaml"],
            "the package hard-errors on a missing overlay for -D env=<env>"
        );
    }

    #[test]
    fn nested_arrays_of_tables_pass_straight_through() {
        let root = root("");
        let values = values_for(
            &root,
            &app("[[env]]\nname = 'PORT'\nvalue = '8080'\n\
                 [[env]]\nname = 'SECRET'\nsecretName = 's'\nsecretKey = 'k'\n\
                 [scaler]\nbehavior = { stabilizationWindowSeconds = 300 }\n\
                 [[scaler.triggers]]\ntype = 'nats'\nmetadata = { subject = 'jobs' }\n"),
            None,
        )
        .expect("values");
        for expected in [
            "- name: PORT",
            "value: '8080'",
            "secretKey: k",
            "stabilizationWindowSeconds: 300",
            "- metadata:",
            "subject: jobs",
            "type: nats",
        ] {
            assert!(
                values.contains(expected),
                "missing `{expected}` in\n{values}"
            );
        }
    }

    #[test]
    fn the_kustomization_lists_every_rendered_file_sorted() {
        let mut zerg = app("replicas = 1");
        zerg.name = "zerg-api".into();
        let mut todo = app("replicas = 1");
        todo.name = "todo-api".into();
        assert_eq!(
            kustomization(&root(""), &[zerg, todo]),
            "# GENERATED by `butler k8s gen --root` — DO NOT EDIT BY HAND.\n\
             # One entry per app with a [workload] in its butler.toml, plus the\n\
             # [k8s] extraResources that file lists.\n\
             apiVersion: kustomize.config.k8s.io/v1beta1\n\
             kind: Kustomization\n\
             resources:\n  \
               - todo-api.yaml\n  \
               - zerg-api.yaml\n"
        );
    }

    /// Environment fixtures the package cannot render ride along in the
    /// aggregate; nothing else may inject a resource into it.
    #[test]
    fn extra_resources_are_appended_after_the_apps() {
        let mut only = app("replicas = 1");
        only.name = "zerg-api".into();
        // `extraResources` belongs to `[k8s]`, so it cannot ride on the shared
        // `root()` helper: that appends after `[k8s.imageTag]`.
        let cfg: Root = toml::from_str(
            "registry = 'acme'\n\
             [k8s]\ntag = '0.1.2'\nextraResources = ['../dev/app-secrets.yaml']\n",
        )
        .expect("test root config parses");
        assert_eq!(
            kustomization(&cfg, &[only])
                .lines()
                .skip_while(|l| *l != "resources:")
                .collect::<Vec<_>>(),
            vec![
                "resources:",
                "  - zerg-api.yaml",
                "  - ../dev/app-secrets.yaml"
            ]
        );
    }

    #[test]
    fn the_render_command_pins_the_package_version() {
        assert_eq!(
            render_command(&root("")),
            "kcl run \"oci://docker.io/yurikrupnik/app?tag=0.1.2\" -D env=dev -q"
        );
    }

    #[test]
    fn tilt_forwards_to_the_merged_port() {
        let root = root("[workloadDefaults.web]\nport = 8080\n");
        let app: App =
            toml::from_str("[workload]\nport = 3000\n[env.prod.workload]\nport = 9000\n")
                .expect("app config");
        let dev = merged_workload(&root, &app, tilt::Kind::Web, "dev").expect("workload");
        assert_eq!(workload_port(&dev), 3000);
        let prod = merged_workload(&root, &app, tilt::Kind::Web, "prod").expect("workload");
        assert_eq!(workload_port(&prod), 9000);
        // An app that declares no port at all gets the package's default.
        let bare: App = toml::from_str("[workload]\nreplicas = 1\n").expect("app config");
        let merged = merged_workload(&root, &bare, tilt::Kind::Service, "dev").expect("workload");
        assert_eq!(workload_port(&merged), DEFAULT_PORT);
    }

    #[test]
    fn the_product_segment_names_the_namespace() {
        assert_eq!(product("apps/todo/api"), "todo");
        assert_eq!(product("apps/zerg/email-nats"), "zerg");
        assert_eq!(product("libs/database"), "database");
        assert_eq!(product("."), "default");
    }
}
