//! `butler submodule gen` — the Kubernetes objects that deploy each submodule.
//!
//! ```text
//! <outDir>/<name>.flux.yaml       Flux GitRepository (always) + Kustomization
//!                                 (when [submodule.<name>] kustomize is set)
//! <outDir>/<name>.yaml            [submodule.<name>.workload] rendered by the
//!                                 `app` KCL package, like an app's [workload]
//! <outDir>/kustomization.yaml     the aggregate
//! ```
//!
//! `<outDir>` is the root butler.toml `[submodules] outDir`, owned outright: a
//! generated file there that no submodule produces any more is deleted by
//! `gen` and reported as drift by `--check`.
//!
//! The source pins the commit this repo's index records for the submodule
//! (`track = "commit"`, the default), so bumping a submodule here is what
//! moves its deployment.
//!
//! YAML is built from `serde_yaml_ng::Mapping` (insertion-ordered), never from
//! `serde_json::Value`: that one's key order depends on whether some other
//! crate in the build enabled `preserve_order`, and a generated file whose
//! bytes depend on the build set would fail `--check` at random.

use std::collections::BTreeMap;
use std::path::Path;

use eyre::{Result, bail, eyre};
use serde::Serialize;
use serde_yaml_ng::{Mapping, Value as Y};

use super::{Checkout, GITMODULES, Submodule};
use crate::settings::{self, Root, SubmoduleDeploy, Track};
use crate::{k8s, tilt};

const GENERATED: &str = "# GENERATED by `butler submodule gen` — DO NOT EDIT BY HAND.";

/// What every butler generator's header starts with — `butler k8s gen` renders
/// the workload files, `butler submodule gen` the rest. Only files carrying it
/// are ever pruned.
const GENERATED_BY_BUTLER: &str = "# GENERATED by `butler ";

/// `[submodules] outDir` with `{env}` expanded.
pub fn out_dir(root: &Root) -> String {
    root.submodules.out_dir.replace("{env}", &root.env)
}

/// The files one generation produces, and the stale ones it removes.
pub struct Plan {
    pub out_dir: String,
    /// Workspace-root-relative path -> content.
    pub files: BTreeMap<String, String>,
    /// Generated files in `out_dir` that nothing produces any more.
    pub stale: Vec<String>,
}

/// What [`Plan::apply`] changed on disk.
#[derive(Debug, Default, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GenReport {
    pub written: Vec<String>,
    pub removed: Vec<String>,
    pub unchanged: usize,
}

pub fn plan(workspace_root: &Path, root: &Root, subs: &[Submodule]) -> Result<Plan> {
    let dir = out_dir(root);
    if dir.trim_end_matches('/') == k8s::out_dir(root).trim_end_matches('/') {
        bail!(
            "{file}: [submodules] outDir and [k8s] outDir are both `{dir}`; \
             `butler submodule gen` prunes its directory, so it needs one of its own",
            file = settings::FILE
        );
    }
    for name in root.submodule.keys() {
        if !subs.iter().any(|s| s.name == *name) {
            let known: Vec<&str> = subs.iter().map(|s| s.name.as_str()).collect();
            bail!(
                "{file} declares [submodule.{name}], but {GITMODULES} has no submodule \
                 named `{name}` (known: {known})",
                file = settings::FILE,
                known = if known.is_empty() {
                    "none".to_string()
                } else {
                    known.join(", ")
                },
            );
        }
    }

    let unconfigured = SubmoduleDeploy::default();
    let mut owners: BTreeMap<String, &str> = BTreeMap::new();
    let mut files = BTreeMap::new();
    for sub in subs {
        let deploy = root.submodule.get(&sub.name).unwrap_or(&unconfigured);
        let name = k8s_name(&sub.name)?;
        if let Some(other) = owners.insert(name.clone(), &sub.name) {
            bail!(
                "submodules `{other}` and `{}` both become the k8s name `{name}`; \
                 re-add one under another `--name`",
                sub.name
            );
        }
        let namespace = deploy.namespace.clone().unwrap_or_else(|| name.clone());
        files.insert(
            format!("{dir}/{name}.flux.yaml"),
            flux(workspace_root, root, sub, deploy, &name, &namespace)?,
        );
        if let Some(workload) = &deploy.workload {
            files.insert(
                format!("{dir}/{name}.yaml"),
                rendered_workload(
                    workspace_root,
                    root,
                    sub,
                    deploy,
                    workload,
                    &name,
                    &namespace,
                )?,
            );
        }
    }
    files.insert(
        format!("{dir}/kustomization.yaml"),
        kustomization(&dir, &files),
    );

    let stale = stale(workspace_root, &dir, &files)?;
    Ok(Plan {
        out_dir: dir,
        files,
        stale,
    })
}

impl Plan {
    /// Drift gate: every generated file on disk byte-identical, nothing stale.
    pub fn drift(&self, workspace_root: &Path) -> Vec<String> {
        let mut drifted = tilt::check_files(workspace_root, &self.files);
        drifted.extend(
            self.stale
                .iter()
                .map(|s| format!("{s}: stale, no submodule generates it")),
        );
        drifted
    }

    /// Write what changed and delete what is stale. Unchanged files are not
    /// rewritten.
    pub fn apply(&self, workspace_root: &Path) -> Result<GenReport> {
        let mut report = GenReport::default();
        for (rel, content) in &self.files {
            let path = workspace_root.join(rel);
            if std::fs::read_to_string(&path).is_ok_and(|on_disk| on_disk == *content) {
                report.unchanged += 1;
                continue;
            }
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| eyre!("creating {}: {e}", parent.display()))?;
            }
            std::fs::write(&path, content).map_err(|e| eyre!("writing {rel}: {e}"))?;
            report.written.push(rel.clone());
        }
        for rel in &self.stale {
            std::fs::remove_file(workspace_root.join(rel))
                .map_err(|e| eyre!("removing stale {rel}: {e}"))?;
            report.removed.push(rel.clone());
        }
        Ok(report)
    }
}

// ---------------------------------------------------------------------------
// Flux

fn flux(
    workspace_root: &Path,
    root: &Root,
    sub: &Submodule,
    deploy: &SubmoduleDeploy,
    name: &str,
    namespace: &str,
) -> Result<String> {
    let url = flux_url(&sub.url).map_err(|e| eyre!("submodule `{}`: {e}", sub.name))?;
    let flux_ns = root.submodules.flux_namespace.as_str();
    let interval = root.submodules.interval.as_str();

    let mut git_ref = Mapping::new();
    match deploy.track {
        Track::Commit => {
            let commit = sub.pinned.as_deref().ok_or_else(|| {
                eyre!(
                    "submodule `{}`: the index has no gitlink for {}, so there is no \
                     commit to pin; `git add {}` it, or set track = \"branch\"",
                    sub.name,
                    sub.path,
                    sub.path
                )
            })?;
            // Flux clones this branch shallowly and checks out the commit.
            if let Some(branch) = &sub.branch {
                git_ref.insert(s("branch"), s(branch));
            }
            git_ref.insert(s("commit"), s(commit));
        }
        Track::Branch => {
            let branch = sub.branch.as_deref().ok_or_else(|| {
                eyre!(
                    "{file} [submodule.{n}] tracks its branch, but {GITMODULES} sets \
                     none; `butler submodule set {n} --branch <branch>`",
                    file = settings::FILE,
                    n = sub.name
                )
            })?;
            git_ref.insert(s("branch"), s(branch));
        }
    }

    let mut docs = vec![object(
        "source.toolkit.fluxcd.io/v1",
        "GitRepository",
        name,
        flux_ns,
        map([
            ("interval", s(interval)),
            ("url", s(&url)),
            ("ref", Y::Mapping(git_ref)),
        ]),
    )];
    if let Some(path) = &deploy.kustomize {
        let path = kustomize_path(workspace_root, sub, path)?;
        docs.push(object(
            "kustomize.toolkit.fluxcd.io/v1",
            "Kustomization",
            name,
            flux_ns,
            map([
                ("interval", s(interval)),
                ("path", s(&path)),
                ("prune", Y::Bool(true)),
                (
                    "sourceRef",
                    map([("kind", s("GitRepository")), ("name", s(name))]),
                ),
                ("targetNamespace", s(namespace)),
            ]),
        ));
    }

    let config = if root.submodule.contains_key(&sub.name) {
        format!(" + {} [submodule.{}]", settings::FILE, sub.name)
    } else {
        String::new()
    };
    let mut out = format!(
        "{GENERATED}\n# Source: {GITMODULES} [submodule \"{}\"]{config}.\n",
        sub.name
    );
    for (i, doc) in docs.iter().enumerate() {
        if i > 0 {
            out.push_str("---\n");
        }
        out.push_str(
            &serde_yaml_ng::to_string(doc)
                .map_err(|e| eyre!("serialising {name}'s Flux objects: {e}"))?,
        );
    }
    Ok(out)
}

/// A URL Flux can fetch. `.gitmodules` also allows relative URLs (resolved
/// against this repo's remote) and local paths, which mean nothing inside the
/// cluster; scp-style `git@host:org/repo` is rewritten to the `ssh://` form
/// Flux requires.
fn flux_url(url: &str) -> Result<String> {
    if let Some((scheme, _)) = url.split_once("://") {
        return match scheme {
            "https" | "http" | "ssh" => Ok(url.to_string()),
            other => bail!("Flux fetches over https or ssh, but `{url}` uses {other}"),
        };
    }
    if let Some((host, path)) = url.split_once(':')
        && !host.is_empty()
        && !host.contains('/')
        && !path.is_empty()
    {
        return Ok(format!("ssh://{host}/{}", path.trim_start_matches('/')));
    }
    bail!(
        "`{url}` is a relative or local path, which Flux cannot fetch; give the \
         submodule an absolute https:// or ssh:// url (`butler submodule set <name> --url ...`)"
    )
}

/// `./<path>` inside the submodule's repository, as Flux wants it. Checked
/// against the checkout when there is one, so a typo fails here instead of in
/// the cluster.
fn kustomize_path(workspace_root: &Path, sub: &Submodule, path: &str) -> Result<String> {
    let clean = path.trim().trim_start_matches("./").trim_end_matches('/');
    if clean.starts_with('/') || clean.split('/').any(|seg| seg == "..") {
        bail!(
            "{} [submodule.{}] kustomize = `{path}` must be a path inside the submodule",
            settings::FILE,
            sub.name
        );
    }
    if sub.checkout != Checkout::Uninitialized {
        let dir = workspace_root.join(&sub.path).join(clean);
        let found = ["kustomization.yaml", "kustomization.yml", "Kustomization"]
            .iter()
            .any(|f| dir.join(f).is_file());
        if !found {
            bail!(
                "{} [submodule.{}] kustomize = `{path}`: no kustomization in {}/{clean}",
                settings::FILE,
                sub.name,
                sub.path
            );
        }
    }
    Ok(if clean.is_empty() {
        "./".to_string()
    } else {
        format!("./{clean}")
    })
}

// ---------------------------------------------------------------------------
// KCL workload

/// Render `[submodule.<name>.workload]` through the same package, merge and
/// image rules as an app's `[workload]`. The values files only feed the
/// render: writing them into the submodule would dirty another repo.
#[allow(clippy::too_many_arguments)]
fn rendered_workload(
    workspace_root: &Path,
    root: &Root,
    sub: &Submodule,
    deploy: &SubmoduleDeploy,
    workload: &toml::Value,
    name: &str,
    namespace: &str,
) -> Result<String> {
    let file = format!("{} [submodule.{}]", settings::FILE, sub.name);
    let kind = tilt::app_kind(workspace_root, &sub.path).ok_or_else(|| {
        if sub.checkout == Checkout::Uninitialized {
            eyre!(
                "{file}: a [workload] takes its kind from the submodule's files, but \
                 {} is not checked out; run `butler submodule update {}`",
                sub.path,
                sub.name
            )
        } else {
            eyre!(
                "{file}: no {markers} in {}; unsupported app kind",
                sub.path,
                markers = tilt::KIND_MARKERS
            )
        }
    })?;
    let image = deploy
        .image
        .clone()
        .unwrap_or_else(|| format!("$REGISTRY/{name}"));
    let mut envs = deploy.env.clone();
    for env in k8s::repo_envs(root) {
        envs.entry(env).or_default();
    }
    let app = k8s::WorkloadApp {
        dir: sub.path.clone(),
        file,
        name: name.to_string(),
        repository: tilt::image_from_tag(&image, &root.registry),
        product: namespace.to_string(),
        kind,
        declared: workload.clone(),
        config: deploy.config.clone(),
        external_secret: deploy.external_secret.clone(),
        envs,
    };
    let values = k8s::values_files(root, &app)?;
    k8s::render(root, &app, &values)
}

// ---------------------------------------------------------------------------
// Aggregate and pruning

fn kustomization(dir: &str, files: &BTreeMap<String, String>) -> String {
    let mut out = format!(
        "{GENERATED}\n\
         # One entry per generated submodule file.\n\
         apiVersion: kustomize.config.k8s.io/v1beta1\n\
         kind: Kustomization\n"
    );
    let prefix = format!("{dir}/");
    let resources: Vec<&str> = files
        .keys()
        .filter_map(|p| p.strip_prefix(&prefix))
        .collect();
    if resources.is_empty() {
        out.push_str("resources: []\n");
    } else {
        out.push_str("resources:\n");
        for r in resources {
            out.push_str("  - ");
            out.push_str(r);
            out.push('\n');
        }
    }
    out
}

fn stale(
    workspace_root: &Path,
    dir: &str,
    files: &BTreeMap<String, String>,
) -> Result<Vec<String>> {
    let Ok(entries) = std::fs::read_dir(workspace_root.join(dir)) else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    for entry in entries.flatten() {
        let file_name = entry.file_name();
        let file_name = file_name.to_string_lossy();
        if !file_name.ends_with(".yaml") {
            continue;
        }
        let rel = format!("{dir}/{file_name}");
        if files.contains_key(&rel) {
            continue;
        }
        let generated = std::fs::read_to_string(entry.path())
            .is_ok_and(|body| body.starts_with(GENERATED_BY_BUTLER));
        if generated {
            out.push(rel);
        }
    }
    out.sort();
    Ok(out)
}

// ---------------------------------------------------------------------------
// Helpers

/// A DNS-1123 label from a submodule name: lowercase alphanumerics and `-`,
/// at most 63 characters (`vendor/My_Lib` -> `vendor-my-lib`).
fn k8s_name(name: &str) -> Result<String> {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        let c = c.to_ascii_lowercase();
        if c.is_ascii_lowercase() || c.is_ascii_digit() {
            out.push(c);
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    out.truncate(63);
    let out = out.trim_matches('-').to_string();
    if out.is_empty() {
        bail!("submodule `{name}` has no characters usable in a k8s name");
    }
    Ok(out)
}

fn s(value: &str) -> Y {
    Y::String(value.to_string())
}

fn map<const N: usize>(pairs: [(&str, Y); N]) -> Y {
    Y::Mapping(pairs.into_iter().map(|(k, v)| (s(k), v)).collect())
}

fn object(api_version: &str, kind: &str, name: &str, namespace: &str, spec: Y) -> Y {
    map([
        ("apiVersion", s(api_version)),
        ("kind", s(kind)),
        (
            "metadata",
            map([("name", s(name)), ("namespace", s(namespace))]),
        ),
        ("spec", spec),
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root(extra: &str) -> Root {
        toml::from_str(&format!("registry = 'acme'\n{extra}")).expect("test root parses")
    }

    fn sub(name: &str, url: &str, branch: Option<&str>) -> Submodule {
        Submodule {
            name: name.into(),
            path: name.into(),
            url: url.into(),
            branch: branch.map(Into::into),
            pinned: Some("0123456789abcdef0123456789abcdef01234567".into()),
            // Not checked out: nothing on disk to validate against.
            checkout: Checkout::Uninitialized,
        }
    }

    fn scratch() -> std::path::PathBuf {
        use std::sync::atomic::{AtomicU32, Ordering};
        static SEQ: AtomicU32 = AtomicU32::new(0);
        let dir = std::env::temp_dir().join(format!(
            "butler-submodule-test-{}-{}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed)
        ));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("scratch dir");
        dir
    }

    #[test]
    fn the_source_pins_the_indexed_commit_and_keeps_the_branch_for_the_clone() {
        let root = root("[submodule.app]\nkustomize = './k8s/base/'\nnamespace = 'apps'\n");
        let dir = scratch();
        let plan = plan(&dir, &root, &[sub("app", "https://g/app", Some("main"))]).expect("plan");
        let flux = &plan.files["manifests/k8s/submodules/app.flux.yaml"];
        let docs: Vec<serde_yaml_ng::Value> = flux
            .split("---\n")
            .map(|d| serde_yaml_ng::from_str(d).expect("valid yaml"))
            .collect();
        assert_eq!(docs[0]["kind"].as_str(), Some("GitRepository"));
        assert_eq!(
            docs[0]["metadata"]["namespace"].as_str(),
            Some("flux-system")
        );
        assert_eq!(
            docs[0]["spec"]["ref"]["commit"].as_str(),
            Some("0123456789abcdef0123456789abcdef01234567")
        );
        assert_eq!(docs[0]["spec"]["ref"]["branch"].as_str(), Some("main"));
        assert_eq!(docs[1]["kind"].as_str(), Some("Kustomization"));
        assert_eq!(docs[1]["spec"]["path"].as_str(), Some("./k8s/base"));
        assert_eq!(docs[1]["spec"]["targetNamespace"].as_str(), Some("apps"));
        assert_eq!(docs[1]["spec"]["sourceRef"]["name"].as_str(), Some("app"));
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn an_unconfigured_submodule_still_gets_a_source_but_no_kustomization() {
        let dir = scratch();
        let plan = plan(
            &dir,
            &root(""),
            &[sub("lib", "git@github.com:o/lib.git", None)],
        )
        .expect("plan");
        let flux = &plan.files["manifests/k8s/submodules/lib.flux.yaml"];
        assert!(!flux.contains("---"), "one document only:\n{flux}");
        assert!(
            flux.contains("url: ssh://git@github.com/o/lib.git"),
            "{flux}"
        );
        assert!(
            plan.files["manifests/k8s/submodules/kustomization.yaml"].contains("  - lib.flux.yaml")
        );
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn tracking_a_branch_needs_one_in_gitmodules() {
        let dir = scratch();
        let err = plan(
            &dir,
            &root("[submodule.app]\ntrack = 'branch'\n"),
            &[sub("app", "https://g/app", None)],
        )
        .err()
        .expect("no branch to track");
        assert!(err.to_string().contains("--branch"), "{err}");
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn config_for_a_submodule_gitmodules_lacks_is_an_error() {
        let dir = scratch();
        let err = plan(
            &dir,
            &root("[submodule.gone]\n"),
            &[sub("app", "https://g/app", None)],
        )
        .err()
        .expect("unknown submodule");
        assert!(err.to_string().contains("[submodule.gone]"), "{err}");
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn urls_flux_cannot_fetch_are_rejected() {
        assert!(flux_url("../sibling.git").is_err());
        assert!(flux_url("/srv/git/x").is_err());
        assert!(flux_url("file:///srv/git/x").is_err());
        assert_eq!(
            flux_url("git@host:/abs/x.git").expect("scp form"),
            "ssh://git@host/abs/x.git"
        );
    }

    #[test]
    fn names_that_collide_as_k8s_names_are_an_error() {
        let dir = scratch();
        let err = plan(
            &dir,
            &root(""),
            &[
                sub("My_Lib", "https://g/a", None),
                sub("my-lib", "https://g/b", None),
            ],
        )
        .err()
        .expect("collision");
        assert!(err.to_string().contains("my-lib"), "{err}");
        let _ = std::fs::remove_dir_all(dir);
    }

    /// Pruning owns only what a butler generator wrote: a hand-written file in
    /// the directory survives, a generated one nothing produces is removed.
    #[test]
    fn only_generated_orphans_are_stale() {
        let dir = scratch();
        let out = dir.join("manifests/k8s/submodules");
        std::fs::create_dir_all(&out).expect("out dir");
        std::fs::write(
            out.join("gone.flux.yaml"),
            format!("{GENERATED}\nkind: X\n"),
        )
        .expect("orphan");
        std::fs::write(out.join("handmade.yaml"), "kind: Namespace\n").expect("handmade");
        let plan = plan(&dir, &root(""), &[]).expect("plan");
        assert_eq!(plan.stale, vec!["manifests/k8s/submodules/gone.flux.yaml"]);
        let _ = std::fs::remove_dir_all(dir);
    }
}
