// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

/**
 * DTO for creating a new task
 */
export type CreateTask = { title: string, description: string, project_id: string | null, priority: TaskPriority, status: TaskStatus, due_date: string | null, };
