// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

/**
 * Task entity - represents a task
 */
export type Task = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Task title
 */
title: string, 
/**
 * Task description
 */
description: string, 
/**
 * Optional project association
 */
project_id: string | null, 
/**
 * Task priority
 */
priority: TaskPriority, 
/**
 * Task status
 */
status: TaskStatus, 
/**
 * Optional due date
 */
due_date: string | null, 
/**
 * Creation timestamp
 */
created_at: string, 
/**
 * Last update timestamp
 */
updated_at: string, };
