// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoPriority } from "./TodoPriority";

/**
 * DTO for creating a todo.
 */
export type CreateTodo = { title: string, description: string, priority: TodoPriority, };
