// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of lifecycle transition an event represents.
 */
export type TodoEventKind = "created" | "updated" | "completed" | "uncompleted" | "deleted";
