// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Todo } from "./Todo";
import type { TodoEventKind } from "./TodoEventKind";

/**
 * A todo lifecycle event. `todo` carries a snapshot for all kinds except
 * `Deleted` (where only the id is known).
 */
export type TodoEvent = { event_id: string, kind: TodoEventKind, todo_id: string, todo: Todo | null, occurred_at: string, };
