// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Todo priority levels (maps to the Postgres `todo_priority` enum).
 */
export type TodoPriority = "low" | "medium" | "high";
