// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoPriority } from "./TodoPriority";

/**
 * A todo item.
 */
export type Todo = { 
/**
 * Unique identifier
 */
id: string, 
/**
 * Short title
 */
title: string, 
/**
 * Optional longer description
 */
description: string, 
/**
 * Whether the todo is completed
 */
completed: boolean, 
/**
 * Priority
 */
priority: TodoPriority, 
/**
 * Creation timestamp (RFC3339)
 */
created_at: string, 
/**
 * Last update timestamp (RFC3339)
 */
updated_at: string, };
