// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TodoPriority } from "./TodoPriority";

/**
 * DTO for updating a todo. All fields optional (PATCH semantics).
 */
export type UpdateTodo = { title: string | null, description: string | null, completed: boolean | null, priority: TodoPriority | null, };
