# vals configuration for GCP Secret Manager
# Usage: vals env -f .vals.yaml
# Docs: https://github.com/helmfile/vals#gcp-secrets-manager

#APP_SECRETS: ref+gcpsecrets://playground-447016/app-secrets
#CRATES_TOKEN: ref+gcpsecrets://playground-447016/crates-token
#DOCKER_PASSWORD: ref+gcpsecrets://playground-447016/docker-secret
#GITHUB_TOKEN: ref+gcpsecrets://playground-447016/github-secret
#MANAGER_SECRETS: ref+gcpsecrets://playground-447016/manager-secrets
#FLAGSMITH_DB_CREDENTIALS: ref+gcpsecrets://playground-447016/flagsmith-db-credentials
OPENAI: ref+gcpsecrets://playground-447016/manager-secrets#/ai/openai
ANTHROPIC: ref+gcpsecrets://playground-447016/manager-secrets#/ai/anthropic
GITHUB1: ref+gcpsecrets://playground-447016/manager-secrets#/github1
#CARGO: ref+gcpsecrets://playground-447016/manager-secrets#/cargo
#CRATE: ref+gcpsecrets://playground-447016/crates-token
DOCKER_SECRET: ref+gcpsecrets://playground-447016/docker-secret
GITHUB_SECRET: ref+gcpsecrets://playground-447016/github-secret

