//! Field selector library for dynamic field selection with role-based access control.
//!
//! This library provides types and traits for implementing field selection
//! in REST APIs with security features like role-based access control.
//!
//! # Features
//!
//! - `axum` - Enables Axum integration with `FromRequestParts` extractor

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::collections::HashSet;
use uuid::Uuid;

/// User roles for authorization.
///
/// Variants are declared in ascending privilege order, so the derived
/// [`Ord`] matches the privilege hierarchy: `Anonymous < User < Admin`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
pub enum UserRole {
    /// Anonymous/unauthenticated user
    #[default]
    Anonymous,
    /// Regular authenticated user
    User,
    /// Administrator with elevated privileges
    Admin,
}

impl UserRole {
    /// Check if this role has at least the required role level
    pub fn has_permission(&self, required: &UserRole) -> bool {
        self >= required
    }
}

/// Authentication context containing user information.
///
/// # Security contract
///
/// This type carries the *result* of authentication; it never performs
/// authentication itself. Server-side auth middleware is responsible for
/// validating credentials (e.g. a JWT) and inserting an `AuthContext` into
/// the request extensions. Anything derived from client-controlled input
/// (headers, query parameters, bodies) MUST NOT be trusted to build a
/// non-anonymous context.
#[derive(Debug, Clone, Default)]
pub struct AuthContext {
    /// User ID (None for anonymous)
    pub user_id: Option<Uuid>,
    /// User role
    pub role: UserRole,
    /// Username (None for anonymous)
    pub username: Option<String>,
}

impl AuthContext {
    /// Create an anonymous context (no authentication)
    pub fn anonymous() -> Self {
        Self::default()
    }

    /// Create an authenticated user context
    pub fn user(user_id: Uuid, username: String) -> Self {
        Self {
            user_id: Some(user_id),
            role: UserRole::User,
            username: Some(username),
        }
    }

    /// Create an admin context
    pub fn admin(user_id: Uuid, username: String) -> Self {
        Self {
            user_id: Some(user_id),
            role: UserRole::Admin,
            username: Some(username),
        }
    }

    /// Check if the user is authenticated
    pub fn is_authenticated(&self) -> bool {
        self.user_id.is_some()
    }

    /// Check if user has required role
    pub fn has_role(&self, required: &UserRole) -> bool {
        self.role.has_permission(required)
    }
}

/// Field access level configuration
#[derive(Debug, Clone)]
pub struct FieldAccess {
    /// Field name
    pub field: &'static str,
    /// Minimum role required to access this field
    pub required_role: UserRole,
}

/// Trait for DTOs that support field selection with security.
/// Implement this to get compile-time field validation and role-based access control.
///
/// Field metadata is `&'static` — implementations (typically generated by the
/// `SelectableFields` derive macro) return borrowed slices and never allocate.
pub trait SelectableFields: Serialize {
    /// Get all available field names for this type
    fn available_fields() -> &'static [&'static str];

    /// Get fields that should NEVER be exposed (blacklist)
    /// These fields will be filtered out regardless of request
    fn restricted_fields() -> &'static [&'static str] {
        &[]
    }

    /// Get role-based field access configuration.
    ///
    /// Fields absent from this list require only [`UserRole::Anonymous`]
    /// (accessible to everyone), so the default of no entries makes every
    /// available field publicly selectable.
    fn field_access() -> &'static [FieldAccess] {
        &[]
    }

    /// Validate that requested fields are valid
    fn validate_fields(fields: &HashSet<&str>) -> Result<(), Vec<String>> {
        let available = Self::available_fields();

        let invalid: Vec<String> = fields
            .iter()
            .filter(|f| !available.iter().any(|a| a == *f))
            .map(|f| (*f).to_string())
            .collect();

        if invalid.is_empty() {
            Ok(())
        } else {
            Err(invalid)
        }
    }

    /// Filter fields based on user role and restrictions
    fn filter_by_role<'a>(fields: &HashSet<&'a str>, auth: &AuthContext) -> HashSet<&'a str> {
        fields
            .iter()
            .filter(|field| {
                // Filter out restricted fields
                if Self::restricted_fields().contains(field) {
                    tracing::warn!(field = **field, "Attempted access to restricted field");
                    return false;
                }

                // Check role-based access
                if let Some(access) = Self::field_access().iter().find(|fa| fa.field == **field)
                    && !auth.has_role(&access.required_role)
                {
                    tracing::warn!(
                        field = **field,
                        user_role = ?auth.role,
                        required_role = ?access.required_role,
                        "Insufficient permissions for field access"
                    );
                    return false;
                }

                true
            })
            .copied()
            .collect()
    }
}

/// Errors that can occur during field selection
#[derive(Debug, thiserror::Error)]
pub enum FieldSelectionError {
    #[error("Invalid fields requested: {0:?}")]
    InvalidFields(Vec<String>),
    #[error("Serialization error: {0}")]
    SerializationError(#[from] serde_json::Error),
}

/// Query parameter extractor for field selection
/// Usage: GET /api/todos?fields=id,name,completed
#[derive(Debug, Clone, Default, Deserialize)]
pub struct FieldSelector {
    #[serde(default)]
    pub fields: Option<String>,
}

impl FieldSelector {
    /// Get the set of requested fields, borrowed from the raw query string
    pub fn get_fields(&self) -> Option<HashSet<&str>> {
        self.fields.as_deref().map(|f| {
            f.split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .collect()
        })
    }

    /// Check if a specific field is requested
    pub fn includes(&self, field: &str) -> bool {
        match self.fields.as_deref() {
            Some(f) => f.split(',').any(|s| s.trim() == field),
            None => true, // If no fields specified, include all
        }
    }

    /// Resolve which fields to include based on the parsed request and auth context
    fn resolve_fields<'a, T>(
        requested: Option<&HashSet<&'a str>>,
        auth: &AuthContext,
    ) -> Result<HashSet<&'a str>, FieldSelectionError>
    where
        T: SelectableFields,
    {
        match requested {
            Some(fields) => {
                // Validate that requested fields exist
                T::validate_fields(fields).map_err(FieldSelectionError::InvalidFields)?;
                // Filter by role and restrictions
                Ok(T::filter_by_role(fields, auth))
            }
            None => {
                // Return all fields the user has access to
                let all_fields: HashSet<&str> = T::available_fields().iter().copied().collect();
                Ok(T::filter_by_role(&all_fields, auth))
            }
        }
    }

    /// Securely filter a serializable value with validation and role-based access control
    pub fn filter_secure<T>(
        &self,
        value: &T,
        auth: &AuthContext,
    ) -> Result<Value, FieldSelectionError>
    where
        T: Serialize + SelectableFields,
    {
        let requested = self.get_fields();
        let fields_to_include = Self::resolve_fields::<T>(requested.as_ref(), auth)?;

        // Log field access for audit
        if let Some(requested) = &requested {
            tracing::info!(
                user_id = ?auth.user_id,
                user_role = ?auth.role,
                requested_fields = ?requested,
                allowed_fields = ?fields_to_include,
                "Field selection applied"
            );
        }

        // Serialize and filter
        let json_value = serde_json::to_value(value)?;

        match json_value {
            Value::Object(obj) => Ok(Value::Object(filter_object(obj, &fields_to_include))),
            value => Ok(value),
        }
    }

    /// Securely filter a list of serializable values
    pub fn filter_list_secure<T>(
        &self,
        values: &[T],
        auth: &AuthContext,
    ) -> Result<Value, FieldSelectionError>
    where
        T: Serialize + SelectableFields,
    {
        let requested = self.get_fields();
        let fields_to_include = Self::resolve_fields::<T>(requested.as_ref(), auth)?;

        // Log field access for audit
        if let Some(requested) = &requested {
            tracing::info!(
                user_id = ?auth.user_id,
                user_role = ?auth.role,
                requested_fields = ?requested,
                allowed_fields = ?fields_to_include,
                count = values.len(),
                "Field selection applied to list"
            );
        }

        let filtered: Result<Vec<Value>, FieldSelectionError> = values
            .iter()
            .map(|v| {
                let json_value = serde_json::to_value(v)?;
                match json_value {
                    Value::Object(obj) => Ok(Value::Object(filter_object(obj, &fields_to_include))),
                    value => Ok(value),
                }
            })
            .collect();

        Ok(Value::Array(filtered?))
    }
}

/// Helper function to filter JSON object by field names
fn filter_object(obj: Map<String, Value>, fields: &HashSet<&str>) -> Map<String, Value> {
    obj.into_iter()
        .filter(|(k, _)| fields.contains(k.as_str()))
        .collect()
}

// Axum integration - only available with the "axum" feature
#[cfg(feature = "axum")]
mod axum_integration {
    use super::*;
    use axum::{extract::FromRequestParts, http::request::Parts};

    /// Extracts [`AuthContext`] from request extensions.
    ///
    /// # Security contract
    ///
    /// A server-side authentication middleware MUST validate the caller's
    /// credentials (e.g. verify a JWT) and insert an [`AuthContext`] into the
    /// request extensions before this extractor runs. This extractor performs
    /// no authentication of its own and never reads client-supplied headers.
    ///
    /// If no `AuthContext` is present in the extensions (middleware missing or
    /// not run), extraction fails CLOSED: the request is treated as
    /// [`AuthContext::anonymous()`], the lowest privilege level.
    impl<S> FromRequestParts<S> for AuthContext
    where
        S: Send + Sync,
    {
        type Rejection = std::convert::Infallible;

        async fn from_request_parts(
            parts: &mut Parts,
            _state: &S,
        ) -> Result<Self, Self::Rejection> {
            Ok(parts
                .extensions
                .get::<AuthContext>()
                .cloned()
                .unwrap_or_else(AuthContext::anonymous))
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[derive(Serialize)]
    struct TestDto {
        id: i32,
        name: String,
        email: String,
    }

    impl SelectableFields for TestDto {
        fn available_fields() -> &'static [&'static str] {
            &["id", "name", "email"]
        }
    }

    #[test]
    fn test_field_selector_filter() {
        let dto = TestDto {
            id: 1,
            name: "test".to_string(),
            email: "test@example.com".to_string(),
        };

        let selector = FieldSelector {
            fields: Some("id,name".to_string()),
        };

        let auth = AuthContext::anonymous();

        let filtered = selector.filter_secure(&dto, &auth).unwrap();
        let obj = filtered.as_object().unwrap();

        assert!(obj.contains_key("id"));
        assert!(obj.contains_key("name"));
        assert!(!obj.contains_key("email"));
    }

    #[test]
    fn test_includes() {
        let selector = FieldSelector {
            fields: Some("id, name".to_string()),
        };
        assert!(selector.includes("id"));
        assert!(selector.includes("name"));
        assert!(!selector.includes("email"));

        let all = FieldSelector::default();
        assert!(all.includes("anything"));
    }

    #[test]
    fn test_user_role_permissions() {
        assert!(UserRole::Admin.has_permission(&UserRole::Admin));
        assert!(UserRole::Admin.has_permission(&UserRole::User));
        assert!(UserRole::Admin.has_permission(&UserRole::Anonymous));

        assert!(!UserRole::User.has_permission(&UserRole::Admin));
        assert!(UserRole::User.has_permission(&UserRole::User));
        assert!(UserRole::User.has_permission(&UserRole::Anonymous));

        assert!(!UserRole::Anonymous.has_permission(&UserRole::Admin));
        assert!(!UserRole::Anonymous.has_permission(&UserRole::User));
        assert!(UserRole::Anonymous.has_permission(&UserRole::Anonymous));
    }

    #[test]
    fn test_auth_context_roles() {
        let anon = AuthContext::anonymous();
        assert!(!anon.is_authenticated());
        assert!(anon.has_role(&UserRole::Anonymous));
        assert!(!anon.has_role(&UserRole::User));

        let user = AuthContext::user(Uuid::now_v7(), "testuser".to_string());
        assert!(user.is_authenticated());
        assert!(user.has_role(&UserRole::User));
        assert!(!user.has_role(&UserRole::Admin));

        let admin = AuthContext::admin(Uuid::now_v7(), "admin".to_string());
        assert!(admin.is_authenticated());
        assert!(admin.has_role(&UserRole::Admin));
    }
}
