apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - ../../../base

namePrefix: postgres-

replicas:
  - name: zerg-db-worker
    count: 1

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: zerg-db-worker-config
    literals:
      - DB_BACKEND=postgres
      - APP_PORT=8081
      - HEALTH_PORT=8081

patches:
  - patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/dapr.io~1app-id
        value: "db-worker-postgres"
    target:
      kind: Deployment
      name: zerg-db-worker
