//! `butler tekton gen` — a Tekton Pipeline for every runnable target.
//!
//! ```text
//! <outDir>/tasks.yaml          the runner Tasks: clone, nx, task, just, nu,
//!                              buildkit, kubectl-apply (only those in use)
//! <outDir>/nx.yaml             one Pipeline per nx `project:target`
//! <outDir>/task.yaml           one per Taskfile task (root file + includes)
//! <outDir>/just.yaml           one per public justfile recipe
//! <outDir>/nu.yaml             one per `.nu` script with a `main`
//! <outDir>/deploy.yaml         one per app with a `[workload]`: the Tilt dev
//!                              loop in-cluster — build the image, apply the
//!                              manifest `butler k8s gen` committed
//! <outDir>/kustomization.yaml  the aggregate
//! ```
//!
//! Every Pipeline is `clone -> run`: it names its target, and the runner Task
//! runs it. Each tool resolves its own dependencies (`nx run` its `dependsOn`,
//! `task` its `deps`), so the Pipeline does not restate that graph — a second
//! copy of it would be one more thing to drift.
//!
//! The target set is derived, never listed; the root `butler.toml` `[tekton]`
//! carries only what cannot be derived: step images, the task/just release to
//! download, the repository URL, and `exclude` globs over target ids
//! (`nx:<project>:<target>`, `task:<name>`, `just:<recipe>`, `nu:<path>`,
//! `deploy:<app>`) for the long-running and interactive ones. An optional
//! `[tekton.taskgraph]` runs every Taskfile task through `taskgraph shim`, so
//! in-cluster runs publish their executions like CI and developer runs do.
//!
//! `<outDir>` is owned outright, like `[submodules] outDir`: a generated file
//! nothing produces any more is deleted by `gen` and is drift for `--check`.

mod sources;
mod tasks;

use std::collections::BTreeMap;
use std::path::Path;

use eyre::{Result, bail, eyre};
use globset::{Glob, GlobSet, GlobSetBuilder};
use serde_yaml_ng::{Mapping, Value as Y};
use sha2::{Digest, Sha256};

use crate::graph::ProjectGraph;
use crate::settings::{self, AppOverrides, Root, Tekton};
use crate::submodule::manifests::{Plan, dns_chars, map, s};
use crate::{hash, k8s, submodule};

const GENERATED: &str = "# GENERATED by `butler tekton gen` — DO NOT EDIT BY HAND.";

const MANAGED_BY: &str = "app.kubernetes.io/managed-by";
const RUNNER_LABEL: &str = "butler/runner";
const TARGET_ANNOTATION: &str = "butler/target";

/// Pipeline names must be DNS-1123 labels: a PipelineRun copies the name into
/// its `tekton.dev/pipeline` label, and label values stop at 63.
const MAX_NAME: usize = 63;

/// Which tool runs a target, and so which runner Task its Pipeline calls.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum Runner {
    Nx,
    Task,
    Just,
    Nu,
}

impl Runner {
    const fn name(self) -> &'static str {
        match self {
            Self::Nx => "nx",
            Self::Task => "task",
            Self::Just => "just",
            Self::Nu => "nu",
        }
    }

    const fn task(self) -> &'static str {
        match self {
            Self::Nx => tasks::NX,
            Self::Task => tasks::TASK,
            Self::Just => tasks::JUST,
            Self::Nu => tasks::NU,
        }
    }

    /// First comment line of the runner's Pipeline file.
    const fn source(self) -> &'static str {
        match self {
            Self::Nx => "One Pipeline per nx project:target in the project graph.",
            Self::Task => "One Pipeline per task of the root Taskfile and its local includes.",
            Self::Just => "One Pipeline per public recipe of the root justfile.",
            Self::Nu => "One Pipeline per .nu script that defines a main.",
        }
    }
}

/// One runnable target.
#[derive(Debug)]
pub(crate) struct Target {
    runner: Runner,
    /// What follows `<runner>:` in the target id: `zerg_api:build`, `check`,
    /// `db::migrate`, `scripts/nu/ide-check.nu`.
    name: String,
    /// The runner Task's params that select this target.
    params: Vec<(&'static str, String)>,
}

impl Target {
    fn id(&self) -> String {
        format!("{}:{}", self.runner.name(), self.name)
    }

    fn command(&self) -> String {
        match self.runner {
            Runner::Nx => format!("bun nx run {}", self.name),
            Runner::Task => format!("task {}", self.name),
            Runner::Just => format!("just {}", self.name),
            Runner::Nu => format!("nu --no-config-file {}", self.name),
        }
    }

    /// The Pipeline name before DNS normalisation.
    fn stem(&self) -> String {
        let name = match self.runner {
            Runner::Nu => self.name.strip_suffix(".nu").unwrap_or(&self.name),
            _ => &self.name,
        };
        format!("{}-{name}", self.runner.name())
    }
}

/// One app's build-and-deploy.
pub(crate) struct Deploy {
    /// Workload name (`zerg-api`): the rendered file's stem and the target id.
    name: String,
    project: String,
    /// Targets of `project` the image build needs first (a web app's `build`).
    prebuild: Vec<String>,
    /// The reference the rendered manifest names, e.g. `yurikrupnik/zerg-api:dev`.
    image: String,
    dockerfile: String,
    context: String,
    stage: String,
    /// `KEY=VALUE`.
    build_args: Vec<String>,
    /// Workspace-relative rendered manifest.
    manifest: String,
}

impl Deploy {
    fn id(&self) -> String {
        format!("deploy:{}", self.name)
    }
}

/// The generated files, and the stale ones in `[tekton] outDir`.
pub fn plan(
    workspace_root: &Path,
    graph: &ProjectGraph,
    root: &Root,
    overrides: &AppOverrides,
    files: &[String],
) -> Result<Plan> {
    let cfg = &root.tekton;
    let out_dir = cfg.out_dir.trim_end_matches('/').to_string();
    for (key, other) in [
        ("[k8s] outDir", k8s::out_dir(root)),
        ("[submodules] outDir", submodule::manifests::out_dir(root)),
    ] {
        if other.trim_end_matches('/') == out_dir {
            bail!(
                "{file}: [tekton] outDir and {key} are both `{out_dir}`; each generator \
                 prunes its directory, so each needs one of its own",
                file = settings::FILE
            );
        }
    }

    let mut targets = sources::nx(graph);
    targets.extend(sources::taskfile(workspace_root)?);
    targets.extend(sources::justfile(workspace_root)?);
    targets.extend(sources::nu(workspace_root, files)?);
    let mut deploys = sources::deploys(workspace_root, graph, root, overrides)?;

    let mut exclude = Exclude::new(&cfg.exclude)?;
    targets.retain(|t| !exclude.hits(&t.id()));
    deploys.retain(|d| !exclude.hits(&d.id()));
    exclude.all_used()?;

    let mut names = Names::default();
    let mut pipelines: BTreeMap<Runner, BTreeMap<String, Y>> = BTreeMap::new();
    for target in &targets {
        let name = names.claim(&target.stem(), &target.id())?;
        let doc = runner_pipeline(cfg, target, &name);
        pipelines
            .entry(target.runner)
            .or_default()
            .insert(name, doc);
    }
    let mut deploy_docs = BTreeMap::new();
    for deploy in &deploys {
        let name = names.claim(&format!("deploy-{}", deploy.name), &deploy.id())?;
        let doc = deploy_pipeline(cfg, deploy, &name);
        deploy_docs.insert(name, doc);
    }

    let mut out = BTreeMap::new();
    let mut resources = Vec::new();
    let mut emit = |file: &str, header: &str, docs: Vec<&Y>| -> Result<()> {
        out.insert(format!("{out_dir}/{file}"), render(header, &docs)?);
        resources.push(file.to_string());
        Ok(())
    };

    let task_docs = runner_tasks(cfg, &pipelines, &deploys)?;
    if !task_docs.is_empty() {
        emit(
            "tasks.yaml",
            &format!(
                "The runner Tasks the Pipelines here call. Step images: {} [tekton.images].",
                settings::FILE
            ),
            task_docs.iter().collect(),
        )?;
    }
    for (runner, docs) in &pipelines {
        emit(
            &format!("{}.yaml", runner.name()),
            runner.source(),
            docs.values().collect(),
        )?;
    }
    if !deploy_docs.is_empty() {
        emit(
            "deploy.yaml",
            "Per app with a [workload]: build its image, apply the manifest `butler k8s gen` rendered.",
            deploy_docs.values().collect(),
        )?;
    }
    out.insert(
        format!("{out_dir}/kustomization.yaml"),
        kustomization(cfg, &resources),
    );
    Plan::owned(workspace_root, out_dir, out)
}

/// The runner Tasks some generated Pipeline calls, clone first.
fn runner_tasks(
    cfg: &Tekton,
    pipelines: &BTreeMap<Runner, BTreeMap<String, Y>>,
    deploys: &[Deploy],
) -> Result<Vec<Y>> {
    if pipelines.is_empty() && deploys.is_empty() {
        return Ok(Vec::new());
    }
    let images = &cfg.images;
    let count = |runner: Runner| pipelines.get(&runner).map_or(0, BTreeMap::len);
    let mut out = vec![tasks::git_clone(image(
        images.git.as_ref(),
        "git",
        "every Pipeline's clone",
    )?)];
    if count(Runner::Nx) > 0 || deploys.iter().any(|d| !d.prebuild.is_empty()) {
        out.push(tasks::nx(image(
            images.nx.as_ref(),
            "nx",
            "the nx targets",
        )?));
    }
    if count(Runner::Task) > 0 {
        let why = format!("{} Taskfile tasks", count(Runner::Task));
        out.push(tasks::go_task(
            image(images.task.as_ref(), "task", &why)?,
            &tasks::Release {
                fetch_image: image(images.fetch.as_ref(), "fetch", &why)?,
                version: version(cfg.task_version.as_ref(), "taskVersion", &why)?,
            },
            cfg.taskgraph.as_ref(),
        ));
    }
    if count(Runner::Just) > 0 {
        let why = format!("{} just recipes", count(Runner::Just));
        out.push(tasks::just(
            image(images.just.as_ref(), "just", &why)?,
            &tasks::Release {
                fetch_image: image(images.fetch.as_ref(), "fetch", &why)?,
                version: version(cfg.just_version.as_ref(), "justVersion", &why)?,
            },
        ));
    }
    if count(Runner::Nu) > 0 {
        let why = format!("{} nu scripts", count(Runner::Nu));
        out.push(tasks::nu(
            image(images.nu.as_ref(), "nu", &why)?,
            &tasks::Release {
                fetch_image: image(images.fetch.as_ref(), "fetch", &why)?,
                version: version(cfg.nu_version.as_ref(), "nuVersion", &why)?,
            },
        ));
    }
    if !deploys.is_empty() {
        out.push(tasks::buildkit(image(
            images.buildkit.as_ref(),
            "buildkit",
            "the deploy Pipelines",
        )?));
        out.push(tasks::kubectl_apply(image(
            images.kubectl.as_ref(),
            "kubectl",
            "the deploy Pipelines",
        )?));
    }
    Ok(out)
}

fn image<'a>(value: Option<&'a String>, key: &str, needed_by: &str) -> Result<&'a str> {
    value.map(String::as_str).ok_or_else(|| {
        eyre!(
            "{file} [tekton.images] has no `{key}`, which {needed_by} need",
            file = settings::FILE
        )
    })
}

fn version<'a>(value: Option<&'a String>, key: &str, needed_by: &str) -> Result<&'a str> {
    value.map(String::as_str).ok_or_else(|| {
        eyre!(
            "{file} [tekton] has no `{key}`: {needed_by} need that release downloaded",
            file = settings::FILE
        )
    })
}

// ---------------------------------------------------------------------------
// Pipelines

fn runner_pipeline(cfg: &Tekton, target: &Target, name: &str) -> Y {
    let mut params: Vec<Y> = target
        .params
        .iter()
        .map(|(k, v)| param_value(k, s(v)))
        .collect();
    params.push(param_value(
        "args",
        Y::Sequence(vec![s("$(params.args[*])")]),
    ));
    if target.runner == Runner::Task && cfg.taskgraph.is_some() {
        // The traced runner's CI origin. A Task sees only its own TaskRun, so
        // the PipelineRun comes in as a param, and the commit from the clone.
        params.push(param_value(
            tasks::PIPELINE_RUN,
            s("$(context.pipelineRun.name)"),
        ));
        params.push(param_value(
            tasks::COMMIT,
            s(&format!("$(tasks.clone.results.{})", tasks::COMMIT)),
        ));
    }
    let mut spec_params = clone_params(cfg);
    spec_params.push(map([
        ("name", s("args")),
        ("type", s("array")),
        ("description", s("Extra arguments after the target.")),
        ("default", Y::Sequence(Vec::new())),
    ]));
    pipeline(
        name,
        target.runner.name(),
        &target.id(),
        &target.command(),
        spec_params,
        vec![source_workspace()],
        vec![
            clone_task(),
            pipeline_task(
                "run",
                target.runner.task(),
                &["clone".to_string()],
                params,
                vec![bind(tasks::SOURCE)],
            ),
        ],
    )
}

fn deploy_pipeline(cfg: &Tekton, deploy: &Deploy, name: &str) -> Y {
    let mut steps = vec![clone_task()];
    let mut image_after = vec!["clone".to_string()];
    if !deploy.prebuild.is_empty() {
        image_after.clear();
    }
    for target in &deploy.prebuild {
        let step = format!("nx-{}", dns_chars(target));
        steps.push(pipeline_task(
            &step,
            tasks::NX,
            &["clone".to_string()],
            vec![
                param_value("project", s(&deploy.project)),
                param_value("target", s(target)),
            ],
            vec![bind(tasks::SOURCE)],
        ));
        image_after.push(step);
    }
    steps.push(pipeline_task(
        "image",
        tasks::BUILDKIT,
        &image_after,
        vec![
            param_value("image", s(&deploy.image)),
            param_value("dockerfile", s(&deploy.dockerfile)),
            param_value("context", s(&deploy.context)),
            param_value("target", s(&deploy.stage)),
            param_value(
                "build-args",
                Y::Sequence(deploy.build_args.iter().map(|a| s(a)).collect()),
            ),
        ],
        vec![bind(tasks::SOURCE), bind(tasks::DOCKERCONFIG)],
    ));
    steps.push(pipeline_task(
        "deploy",
        tasks::APPLY,
        &["image".to_string()],
        vec![
            param_value("manifest", s(&deploy.manifest)),
            param_value("image", s(&deploy.image)),
            param_value("digest", s("$(tasks.image.results.digest)")),
        ],
        vec![bind(tasks::SOURCE)],
    ));
    pipeline(
        name,
        "deploy",
        &deploy.id(),
        &format!(
            "Build {} ({}, stage {}), then apply {} pinned to its digest.",
            deploy.image, deploy.dockerfile, deploy.stage, deploy.manifest
        ),
        clone_params(cfg),
        vec![
            source_workspace(),
            map([
                ("name", s(tasks::DOCKERCONFIG)),
                (
                    "description",
                    s("Registry credentials for the push: a docker config.json."),
                ),
                ("optional", Y::Bool(true)),
            ]),
        ],
        steps,
    )
}

fn pipeline(
    name: &str,
    runner: &str,
    id: &str,
    description: &str,
    params: Vec<Y>,
    workspaces: Vec<Y>,
    tasks: Vec<Y>,
) -> Y {
    let mut labels = Mapping::new();
    labels.insert(s(RUNNER_LABEL), s(runner));
    let mut annotations = Mapping::new();
    annotations.insert(s(TARGET_ANNOTATION), s(id));
    object(
        "Pipeline",
        name,
        labels,
        annotations,
        map([
            ("description", s(description)),
            ("params", Y::Sequence(params)),
            ("workspaces", Y::Sequence(workspaces)),
            ("tasks", Y::Sequence(tasks)),
        ]),
    )
}

fn clone_params(cfg: &Tekton) -> Vec<Y> {
    let mut url = Mapping::new();
    url.insert(s("name"), s("url"));
    url.insert(s("type"), s("string"));
    url.insert(s("description"), s("Git URL to clone."));
    if let Some(repository) = &cfg.repository {
        url.insert(s("default"), s(repository));
    }
    vec![
        Y::Mapping(url),
        map([
            ("name", s("revision")),
            ("type", s("string")),
            ("description", s("Branch, tag or commit to run.")),
            ("default", s(&cfg.revision)),
        ]),
    ]
}

fn source_workspace() -> Y {
    map([
        ("name", s(tasks::SOURCE)),
        ("description", s("Scratch space for the checkout.")),
    ])
}

fn clone_task() -> Y {
    pipeline_task(
        "clone",
        tasks::CLONE,
        &[],
        vec![
            param_value("url", s("$(params.url)")),
            param_value("revision", s("$(params.revision)")),
        ],
        vec![bind(tasks::SOURCE)],
    )
}

fn pipeline_task(
    name: &str,
    task: &str,
    run_after: &[String],
    params: Vec<Y>,
    workspaces: Vec<Y>,
) -> Y {
    let mut out = Mapping::new();
    out.insert(s("name"), s(name));
    if !run_after.is_empty() {
        out.insert(
            s("runAfter"),
            Y::Sequence(run_after.iter().map(|r| s(r)).collect()),
        );
    }
    // `kind` spelled out: the admission webhook defaults it, and an object
    // that differs from its own default is re-patched on every apply.
    out.insert(s("taskRef"), map([("name", s(task)), ("kind", s("Task"))]));
    out.insert(s("params"), Y::Sequence(params));
    out.insert(s("workspaces"), Y::Sequence(workspaces));
    Y::Mapping(out)
}

fn param_value(name: &str, value: Y) -> Y {
    map([("name", s(name)), ("value", value)])
}

/// A Pipeline workspace handed to a task under the same name.
fn bind(workspace: &str) -> Y {
    map([("name", s(workspace)), ("workspace", s(workspace))])
}

/// A `tekton.dev/v1` object; every one carries the managed-by label.
fn object(kind: &str, name: &str, labels: Mapping, annotations: Mapping, spec: Y) -> Y {
    let mut all_labels = Mapping::new();
    all_labels.insert(s(MANAGED_BY), s("butler"));
    all_labels.extend(labels);
    let mut metadata = Mapping::new();
    metadata.insert(s("name"), s(name));
    metadata.insert(s("labels"), Y::Mapping(all_labels));
    if !annotations.is_empty() {
        metadata.insert(s("annotations"), Y::Mapping(annotations));
    }
    map([
        ("apiVersion", s("tekton.dev/v1")),
        ("kind", s(kind)),
        ("metadata", Y::Mapping(metadata)),
        ("spec", spec),
    ])
}

// ---------------------------------------------------------------------------
// Files

fn render(header: &str, docs: &[&Y]) -> Result<String> {
    let mut out = format!("{GENERATED}\n# {header}\n");
    for (i, doc) in docs.iter().enumerate() {
        if i > 0 {
            out.push_str("---\n");
        }
        out.push_str(
            &serde_yaml_ng::to_string(doc).map_err(|e| eyre!("serialising Tekton objects: {e}"))?,
        );
    }
    Ok(out)
}

fn kustomization(cfg: &Tekton, resources: &[String]) -> String {
    let mut out = format!(
        "{GENERATED}\n\
         # Every Tekton file `butler tekton gen` writes.\n\
         apiVersion: kustomize.config.k8s.io/v1beta1\n\
         kind: Kustomization\n"
    );
    if let Some(namespace) = &cfg.namespace {
        out.push_str(&format!("namespace: {namespace}\n"));
    }
    if resources.is_empty() {
        out.push_str("resources: []\n");
    } else {
        out.push_str("resources:\n");
        for r in resources {
            out.push_str(&format!("  - {r}\n"));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Names and exclusions

/// Pipeline names, each claimed by exactly one target id.
#[derive(Default)]
struct Names(BTreeMap<String, String>);

impl Names {
    fn claim(&mut self, stem: &str, id: &str) -> Result<String> {
        let name = resource_name(stem, id);
        if name.is_empty() {
            bail!("target `{id}` has no characters usable in a Tekton name");
        }
        if let Some(other) = self.0.insert(name.clone(), id.to_string()) {
            bail!(
                "targets `{other}` and `{id}` both become the Pipeline `{name}`; \
                 add one to {file} [tekton] exclude",
                file = settings::FILE
            );
        }
        Ok(name)
    }
}

/// `stem` as a DNS-1123 label. Past 63 characters it is cut and suffixed with
/// a hash of the full target id, so two long ids sharing a prefix stay apart.
fn resource_name(stem: &str, id: &str) -> String {
    let name = dns_chars(stem);
    if name.len() <= MAX_NAME {
        return name;
    }
    let digest = hash::hex(&Sha256::digest(id.as_bytes()));
    // 8 hex digits plus the joining `-`; `dns_chars` output is ASCII, so any
    // byte index is a char boundary.
    let head = name[..MAX_NAME - 9].trim_end_matches('-');
    format!("{head}-{}", &digest[..8])
}

/// `[tekton] exclude`, tracking which globs matched anything.
struct Exclude<'a> {
    patterns: &'a [String],
    set: GlobSet,
    used: Vec<bool>,
}

impl<'a> Exclude<'a> {
    fn new(patterns: &'a [String]) -> Result<Self> {
        let mut builder = GlobSetBuilder::new();
        for p in patterns {
            builder.add(
                Glob::new(p).map_err(|e| {
                    eyre!("{file} [tekton] exclude `{p}`: {e}", file = settings::FILE)
                })?,
            );
        }
        Ok(Self {
            patterns,
            set: builder
                .build()
                .map_err(|e| eyre!("{file} [tekton] exclude: {e}", file = settings::FILE))?,
            used: vec![false; patterns.len()],
        })
    }

    fn hits(&mut self, id: &str) -> bool {
        let matched = self.set.matches(id);
        for &i in &matched {
            self.used[i] = true;
        }
        !matched.is_empty()
    }

    fn all_used(&self) -> Result<()> {
        let unused: Vec<&str> = self
            .patterns
            .iter()
            .zip(&self.used)
            .filter(|(_, used)| !**used)
            .map(|(p, _)| p.as_str())
            .collect();
        if !unused.is_empty() {
            bail!(
                "{file} [tekton] exclude: {} match no target; drop them",
                unused.join(", "),
                file = settings::FILE
            );
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[test]
    fn names_are_dns_labels_and_long_ones_stay_distinct() {
        assert_eq!(
            resource_name("nx-zerg_api-build:debug", "x"),
            "nx-zerg-api-build-debug"
        );
        let long = format!("nx-{}", "a".repeat(80));
        let a = resource_name(&format!("{long}-one"), "nx:a:one");
        let b = resource_name(&format!("{long}-two"), "nx:a:two");
        assert!(a.len() <= MAX_NAME && b.len() <= MAX_NAME, "{a} / {b}");
        assert_ne!(a, b);
    }

    #[test]
    fn two_targets_normalising_to_one_name_are_an_error() {
        let mut names = Names::default();
        names
            .claim("nx-a_b-build", "nx:a_b:build")
            .expect("first claim");
        let err = names
            .claim("nx-a-b-build", "nx:a-b:build")
            .expect_err("second claim collides");
        assert!(err.to_string().contains("nx:a_b:build"), "{err}");
    }

    #[test]
    fn exclusion_globs_cover_ids_and_a_dead_glob_is_an_error() {
        let patterns = vec!["nx:*:serve".to_string(), "task:tilt-*".to_string()];
        let mut exclude = Exclude::new(&patterns).expect("globs compile");
        assert!(exclude.hits("nx:zerg_api:serve"));
        assert!(!exclude.hits("nx:zerg_api:build"));
        let err = exclude.all_used().expect_err("task:tilt-* matched nothing");
        assert!(err.to_string().contains("task:tilt-*"), "{err}");
        assert!(exclude.hits("task:tilt-up"));
        exclude.all_used().expect("every glob matched");
    }

    /// The bindings Tekton checks only once a run starts: a Pipeline passes
    /// every param the Task requires and none it does not declare, binds
    /// declared workspaces, and every `$(…)` in a Pipeline or a Task resolves —
    /// a Task cannot see `context.pipelineRun`, and a task result read must be
    /// one an earlier Task declares. For every runner, traced or not.
    #[test]
    fn every_pipeline_binding_and_reference_resolves() {
        for traced in [false, true] {
            let cfg = config(traced);
            let targets = [
                target(
                    Runner::Nx,
                    "api:build",
                    &[("project", "api"), ("target", "build")],
                ),
                target(Runner::Task, "check", &[("task", "check")]),
                target(Runner::Just, "fmt", &[("recipe", "fmt")]),
                target(Runner::Nu, "scripts/x.nu", &[("script", "scripts/x.nu")]),
            ];
            let mut pipelines: BTreeMap<Runner, BTreeMap<String, Y>> = BTreeMap::new();
            for t in &targets {
                let name = t.stem();
                let doc = runner_pipeline(&cfg, t, &name);
                pipelines.entry(t.runner).or_default().insert(name, doc);
            }
            let deploy = Deploy {
                name: "api".into(),
                project: "api".into(),
                prebuild: vec!["build".into()],
                image: "registry/api:dev".into(),
                dockerfile: "Dockerfile".into(),
                context: ".".into(),
                stage: "rust".into(),
                build_args: vec!["APP_NAME=api".into()],
                manifest: "k8s/api.yaml".into(),
            };
            let deploy_doc = deploy_pipeline(&cfg, &deploy, "deploy-api");
            let tasks: BTreeMap<String, Y> =
                runner_tasks(&cfg, &pipelines, std::slice::from_ref(&deploy))
                    .expect("every image and release is configured")
                    .into_iter()
                    .map(|t| (t["metadata"]["name"].as_str().unwrap().to_string(), t))
                    .collect();
            for task in tasks.values() {
                check_task(task);
            }
            for doc in pipelines.values().flat_map(BTreeMap::values) {
                check_pipeline(doc, &tasks);
            }
            check_pipeline(&deploy_doc, &tasks);
        }
    }

    const TASK_CONTEXT: &[&str] = &[
        "context.taskRun.name",
        "context.taskRun.namespace",
        "context.taskRun.uid",
        "context.task.name",
        "context.task.retry-count",
    ];
    const PIPELINE_CONTEXT: &[&str] = &[
        "context.pipelineRun.name",
        "context.pipelineRun.namespace",
        "context.pipelineRun.uid",
        "context.pipeline.name",
        "context.pipelineTask.retries",
    ];

    fn config(traced: bool) -> Tekton {
        let image = |name: &str| Some(format!("{name}:1"));
        Tekton {
            task_version: Some("3.53.1".into()),
            just_version: Some("1.40.0".into()),
            nu_version: Some("0.116.0".into()),
            images: settings::TektonImages {
                git: image("git"),
                fetch: image("fetch"),
                nx: image("nx"),
                task: image("task"),
                just: image("just"),
                nu: image("nu"),
                buildkit: image("buildkit"),
                kubectl: image("kubectl"),
            },
            taskgraph: traced.then(|| settings::TektonTaskgraph {
                release: "https://example.test/releases/download/taskgraph".into(),
                nats_url: "nats://nats:4222".into(),
            }),
            ..Tekton::default()
        }
    }

    fn target(runner: Runner, name: &str, params: &[(&'static str, &str)]) -> Target {
        Target {
            runner,
            name: name.into(),
            params: params.iter().map(|(k, v)| (*k, (*v).to_string())).collect(),
        }
    }

    fn check_task(task: &Y) {
        let name = task["metadata"]["name"].as_str().unwrap();
        let spec = &task["spec"];
        let (params, results, workspaces) = (
            names(&spec["params"]),
            names(&spec["results"]),
            names(&spec["workspaces"]),
        );
        for r in references(&spec["steps"]) {
            let ok = if let Some(p) = name_after(r, "params") {
                params.contains(p)
            } else if let Some(x) = name_after(r, "results") {
                results.contains(x)
            } else if let Some(w) = name_after(r, "workspaces") {
                workspaces.contains(w)
            } else {
                TASK_CONTEXT.contains(&r)
            };
            assert!(ok, "Task {name}: `$({r})` resolves to nothing it declares");
        }
    }

    fn check_pipeline(pipeline: &Y, tasks: &BTreeMap<String, Y>) {
        let name = pipeline["metadata"]["name"].as_str().unwrap();
        let spec = &pipeline["spec"];
        let (params, workspaces) = (names(&spec["params"]), names(&spec["workspaces"]));
        let mut earlier: BTreeMap<&str, &Y> = BTreeMap::new();
        for pt in spec["tasks"].as_sequence().unwrap() {
            let at = format!("Pipeline {name}, task {}", pt["name"].as_str().unwrap());
            let task_ref = pt["taskRef"]["name"].as_str().unwrap();
            let task = &tasks
                .get(task_ref)
                .unwrap_or_else(|| panic!("{at}: no Task {task_ref}"))["spec"];
            let passed = names(&pt["params"]);
            let declared = names(&task["params"]);
            let required: BTreeSet<&str> = task["params"]
                .as_sequence()
                .unwrap()
                .iter()
                .filter(|p| p.get("default").is_none())
                .filter_map(|p| p["name"].as_str())
                .collect();
            assert!(
                passed.is_subset(&declared),
                "{at}: passes {:?}, which {task_ref} does not declare",
                passed.difference(&declared).collect::<Vec<_>>()
            );
            assert!(
                required.is_subset(&passed),
                "{at}: never passes {:?}, which {task_ref} requires",
                required.difference(&passed).collect::<Vec<_>>()
            );
            let task_workspaces = names(&task["workspaces"]);
            for binding in pt["workspaces"].as_sequence().unwrap() {
                let (inner, outer) = (
                    binding["name"].as_str().unwrap(),
                    binding["workspace"].as_str().unwrap(),
                );
                assert!(
                    task_workspaces.contains(inner) && workspaces.contains(outer),
                    "{at}: binds workspace {inner} to {outer}"
                );
            }
            for r in references(&pt["params"]) {
                let ok = if let Some(p) = name_after(r, "params") {
                    params.contains(p)
                } else if let Some(rest) = r.strip_prefix("tasks.") {
                    let (from, result) = rest.split_once(".results.").unwrap();
                    earlier
                        .get(from)
                        .is_some_and(|t| names(&t["results"]).contains(result))
                } else {
                    PIPELINE_CONTEXT.contains(&r)
                };
                assert!(ok, "{at}: `$({r})` resolves to nothing");
            }
            earlier.insert(pt["name"].as_str().unwrap(), task);
        }
    }

    /// The `name` of every entry of a sequence of params/results/workspaces.
    fn names(seq: &Y) -> BTreeSet<&str> {
        seq.as_sequence()
            .into_iter()
            .flatten()
            .filter_map(|entry| entry["name"].as_str())
            .collect()
    }

    /// Every Tekton substitution in the strings under `value`, without its
    /// `$(…)`: `params.args[*]`, `tasks.clone.results.commit`. Shell command
    /// substitutions (`$(uname -m)`) are not Tekton's and are skipped.
    fn references(value: &Y) -> Vec<&str> {
        let mut texts = Vec::new();
        strings(value, &mut texts);
        texts
            .into_iter()
            .flat_map(|text| {
                text.match_indices("$(").filter_map(move |(at, _)| {
                    let rest = &text[at + 2..];
                    Some(&rest[..rest.find(')')?])
                })
            })
            .filter(|r| {
                ["params.", "results.", "workspaces.", "tasks.", "context."]
                    .iter()
                    .any(|kind| r.starts_with(kind))
            })
            .collect()
    }

    fn strings<'a>(value: &'a Y, out: &mut Vec<&'a str>) {
        match value {
            Y::String(text) => out.push(text),
            Y::Sequence(items) => items.iter().for_each(|v| strings(v, out)),
            Y::Mapping(entries) => entries.values().for_each(|v| strings(v, out)),
            _ => {}
        }
    }

    /// `params.args[*]` under `params` is `args`.
    fn name_after<'a>(reference: &'a str, kind: &str) -> Option<&'a str> {
        reference
            .strip_prefix(kind)?
            .strip_prefix('.')?
            .split(['.', '['])
            .next()
    }
}
