apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zerg

resources:
  - ../../../base
  - scaledobject.yaml

namePrefix: influxdb-

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: zerg-db-worker-config
    literals:
      - DB_BACKEND=influxdb
      - APP_PORT=8081
      - HEALTH_PORT=8081
      - INFLUXDB_URL=http://influxdb.dbs.svc.cluster.local:8086
      - INFLUXDB_BUCKET=zerg
      - INFLUXDB_ORG=zerg

patches:
  - patch: |-
      - op: replace
        path: /spec/template/metadata/annotations/dapr.io~1app-id
        value: "db-worker-influxdb"
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
    target:
      kind: Deployment
      name: zerg-db-worker
